import {test,expect} from '@playwright/test';

async function openPreview(page){
  await page.route('**/*',async route=>{
    const url=new URL(route.request().url());
    if(url.hostname==='127.0.0.1'||url.hostname==='localhost')return route.continue();
    if(url.hostname==='restapi.amap.com'&&url.pathname.includes('/v3/direction/walking'))return route.fulfill({contentType:'application/json',body:JSON.stringify({status:'1',route:{paths:[{distance:'1350',duration:'1080',steps:[{polyline:'120.320000,36.060000;120.321000,36.061000;120.322000,36.062000'}]}]}})});
    if(url.hostname==='api.open-meteo.com'&&url.pathname==='/v1/elevation'){const count=(url.searchParams.get('latitude')||'').split(',').filter(Boolean).length;return route.fulfill({contentType:'application/json',body:JSON.stringify({elevation:Array.from({length:count},(_,i)=>20+(i%4)*12)})})}
    if(url.hostname==='api.open-meteo.com'&&url.pathname==='/v1/forecast'){const time=[],apparent_temperature=[],precipitation_probability=[],weather_code=[];for(let hour=0;hour<24;hour++){time.push(`2026-08-10T${String(hour).padStart(2,'0')}:00`);apparent_temperature.push(hour>=10&&hour<=16?34:27);precipitation_probability.push(hour===14?65:15);weather_code.push(hour===14?61:1)}return route.fulfill({contentType:'application/json',body:JSON.stringify({hourly:{time,apparent_temperature,precipitation_probability,weather_code}})})}
    return route.abort();
  });
  await page.goto('/index.html',{waitUntil:'domcontentloaded'});
  await expect(page.locator('#panel')).toBeAttached();await expect(page).toHaveTitle('青岛旅行计划');await expect(page.locator('.eyebrow')).toContainText('v2.4.0');
  await page.evaluate(()=>window.TravelAmapStartup?.hide());await page.waitForTimeout(320);await expect(page.locator('#auditBox')).not.toContainText('页面初始化失败');
}
async function showDayRoute(page){await page.evaluate(()=>{const day=SCHEDULES.find(item=>item.date==='08-10');setDayRouteCard(day);window.TravelLayoutV201?.layoutFloatingUi();window.TravelRouteDrawer?.moveForViewport()});await expect(page.locator('#dayRouteCard')).toHaveClass(/show/)}
async function loadTools(page){await page.locator('[data-tab="tools"]').click();await expect(page.locator('html')).toHaveAttribute('data-trip-tools-loaded','true',{timeout:15000});await expect(page.locator('#todayModePanel')).toBeVisible()}
function overlapArea(a,b){return Math.max(0,Math.min(a.right,b.right)-Math.max(a.left,b.left))*Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top))}
function isDesktop(name){return name.startsWith('desktop')}

test('desktop v2.4 preserves visuals and exposes explicit contexts, service envelopes and lazy tools',async({page},testInfo)=>{
  test.skip(!isDesktop(testInfo.project.name),'Desktop-only layout test');const pageErrors=[];page.on('pageerror',error=>pageErrors.push(error.message));await openPreview(page);await showDayRoute(page);
  const initial=await page.evaluate(()=>({context:Boolean(window.TravelAppContext),adapters:window.TravelMapAdapters?.snapshot?.(),services:window.TravelServiceFacade?.snapshot?.(),lazyLoaded:window.TravelLazyTools?.loaded,result:window.TravelServiceResult?.success({sample:true},{source:'test'})}));
  expect(initial.context).toBe(true);expect(initial.adapters.explicitContext).toBe(true);expect(initial.adapters.adapters).toEqual(expect.arrayContaining(['leaflet','amap']));expect(initial.services.shape).toEqual(['ok','data','error','source','cached','reportedAt']);expect(initial.lazyLoaded).toBe(false);expect(initial.result).toMatchObject({ok:true,error:null,source:'test',cached:false});
  const factory=await page.evaluate(()=>{const fake={state:{selectedDay:null,routeVisible:true,recommendationMode:false},leaflet:{map:null,clusters:{clearLayers(){}},routeLayer:{clearLayers(){}},hotelLayer:null,markers:new Map()},L:()=>({}),visiblePoints:()=>[],schedules:()=>[],routePoints:()=>[],routeOrderMap:()=>new Map(),pointById:()=>null,routeMarkerIcon(){},popup(){},directionIcon(){},bearingRotation(){},setDayRouteCard(){}};const adapter=createLeafletTravelAdapter(fake);return{id:adapter.id,sameContext:adapter.context===fake,ready:adapter.ready()}});expect(factory).toEqual({id:'leaflet',sameContext:true,ready:false});
  const geometry=await page.evaluate(()=>{const card=document.getElementById('dayRouteCard'),sequence=card.querySelector('.day-route-seq');return{width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,card:card.getBoundingClientRect().toJSON(),controls:document.querySelector('.basemap-control').getBoundingClientRect().toJSON(),cardScrollHeight:card.scrollHeight,cardClientHeight:card.clientHeight,sequenceScrollWidth:sequence?.scrollWidth||0,sequenceClientWidth:sequence?.clientWidth||0,buttons:[...card.querySelectorAll('[data-route-point]')].map(node=>node.getBoundingClientRect().toJSON())}});expect(geometry.scrollWidth).toBeLessThanOrEqual(geometry.width+1);expect(overlapArea(geometry.card,geometry.controls)).toBe(0);expect(geometry.cardScrollHeight).toBeLessThanOrEqual(geometry.cardClientHeight+1);expect(geometry.sequenceScrollWidth).toBeLessThanOrEqual(geometry.sequenceClientWidth+1);for(const button of geometry.buttons){expect(button.left).toBeGreaterThanOrEqual(geometry.card.left-1);expect(button.right).toBeLessThanOrEqual(geometry.card.right+1);expect(button.bottom).toBeLessThanOrEqual(geometry.card.bottom+1)}
  await loadTools(page);for(const id of ['todayModePanel','stopStatusPanel','comfortPanel','rainAlternativePanel','taxiBudgetPanel','dailyCardPanel','calendarExportPanel','localDataPanel','dataStatusPanel'])await expect(page.locator('#'+id)).toBeVisible();
  const occurrence=await page.evaluate(()=>{const day=SCHEDULES.find(item=>new Set(item.route).size<item.route.length),counts={};let duplicate='';for(const id of day.route){counts[id]=(counts[id]||0)+1;if(counts[id]>1){duplicate=id;break}}TravelTripOperations.setStop(day.date,duplicate,0,'completed');TravelTripOperations.setStop(day.date,duplicate,1,'skipped');return{first:TravelTripOperations.stopValue(day.date,duplicate,0),second:TravelTripOperations.stopValue(day.date,duplicate,1)}});expect(occurrence.first).toBe('completed');expect(occurrence.second).toBe('skipped');
  await page.locator('#tripToolDaySelect').selectOption('08-10');await expect(page.locator('#comfortContent')).toContainText('可核验步行连接约',{timeout:15000});await expect(page.locator('#comfortContent')).toContainText('累计爬升');await expect(page.locator('#comfortContent')).toContainText('Open-Meteo');await expect(page.locator('#rainAlternativeContent')).toContainText('绕行约');await expect(page.locator('#rainAlternativeContent')).toContainText('最高降水概率 65%');
  const lazyState=await page.evaluate(()=>({loaded:TravelLazyTools.loaded,risk:TravelRiskMetrics.cacheKey,calendar:TravelCalendarExport.build().length,stopKey:TravelTripOperations.keys.STOP_KEY}));expect(lazyState.loaded).toBe(true);expect(lazyState.risk).toBe('trip-risk-metrics-v2.4');expect(lazyState.calendar).toBeGreaterThanOrEqual(5);expect(lazyState.stopKey).toBe('trip-stop-status-v2.4');expect(pageErrors).toEqual([]);await page.screenshot({path:testInfo.outputPath(`${testInfo.project.name}.png`),fullPage:false});
});

test('flagship mobile drawer and lazy tools remain usable without obstruction',async({page},testInfo)=>{
  test.skip(isDesktop(testInfo.project.name),'Mobile device-profile test');await openPreview(page);await showDayRoute(page);await expect(page.locator('html')).toHaveClass(/mobile-layout/);await expect(page.locator('#mobileRouteDrawer')).toHaveAttribute('data-state','half');await expect(page.locator('#mobileRouteDrawer')).toHaveAttribute('data-mode','day');
  const geometry=await page.evaluate(()=>{const drawer=document.getElementById('mobileRouteDrawer'),menu=document.getElementById('menuBtn'),base=document.querySelector('.basemap-control'),r=drawer.getBoundingClientRect(),m=menu.getBoundingClientRect(),b=base.getBoundingClientRect();return{drawer:r.toJSON(),menu:m.toJSON(),base:b.toJSON(),height:innerHeight,width:innerWidth,scrollWidth:document.documentElement.scrollWidth,bottomGap:innerHeight-r.bottom}});expect(geometry.drawer.left).toBeGreaterThanOrEqual(0);expect(geometry.drawer.right).toBeLessThanOrEqual(geometry.width+1);expect(geometry.bottomGap).toBeGreaterThanOrEqual(42);expect(overlapArea(geometry.menu,geometry.base)).toBe(0);expect(geometry.scrollWidth).toBeLessThanOrEqual(geometry.width+1);
  await page.locator('[data-drawer-state="full"]').click();await expect(page.locator('#mobileRouteDrawer')).toHaveAttribute('data-state','full');await page.locator('[data-drawer-state="collapsed"]').click();await page.locator('[data-drawer-state="collapsed"]').click();await expect(page.locator('#mobileRouteDrawer')).toHaveAttribute('data-state','hidden');await expect(page.locator('#mobileRouteSideTab')).toBeVisible();await page.locator('#mobileRouteSideTab').click();await expect(page.locator('#mobileRouteDrawer')).toHaveAttribute('data-state','collapsed');
  await page.locator('#menuBtn').click();await expect.poll(()=>page.evaluate(()=>document.getElementById('panel').getBoundingClientRect().left)).toBeGreaterThanOrEqual(-1);await page.locator('[data-tab="tools"]').click();await expect(page.locator('html')).toHaveAttribute('data-trip-tools-loaded','true',{timeout:15000});await expect(page.locator('#stopStatusPanel')).toBeVisible();await page.locator('#panelEdgeToggle').click();await expect.poll(()=>page.evaluate(()=>document.getElementById('panel').getBoundingClientRect().right)).toBeLessThanOrEqual(1);await page.screenshot({path:testInfo.outputPath(`${testInfo.project.name}.png`),fullPage:false});
});
