import { ItineraryModuleSchema, type ItineraryModule } from '@qingdao/schema';

const NOW = '2026-08-01T00:00:00+08:00';
const SOURCE = 'legacy-v2.5.4-import-review-required';

function module(input: Omit<ItineraryModule, 'schemaVersion' | 'createdAt' | 'updatedAt'>): ItineraryModule {
  return ItineraryModuleSchema.parse({
    schemaVersion: 1,
    createdAt: NOW,
    updatedAt: NOW,
    ...input,
  });
}

export const PHASE3_ITINERARY_MODULES: readonly ItineraryModule[] = [
  module({
    id: 'module-old-city-half-day',
    name: '老城经典半日',
    recommendedDurationMinutes: 300,
    minimumDurationMinutes: 210,
    districts: ['shinan'],
    placeIds: ['signal', 'zhanqiao', 'xiaoyushan', 'qinyu'],
    suitableFor: ['首次到青岛', '情侣', '摄影'],
    fitnessIntensity: 'medium',
    recommendedWindows: [{ start: '08:30', end: '15:30' }],
    openingConstraints: ['开放时间仍需在临近出行日期通过官方来源复核。'],
    weatherConstraints: ['大风或强降雨时优先切换室内 Plan B。'],
    reservationIds: [],
    transportModes: ['walking', 'transit'],
    mealNotes: '老城餐饮不在本模块中写死，保留用户自由选择。',
    restNotes: '山地步行后预留休息。',
    planBModuleIds: ['module-rainy-indoor'],
    sourceRefIds: [SOURCE],
    splittableInto: [],
    mergeableWith: ['module-old-city-coast'],
    conflictsWith: [],
    rationale: '复用 Legacy v2.5.4 已存在点位形成可编辑模块，不新增未经核验事实。',
  }),
  module({
    id: 'module-east-coast-evening',
    name: '东岸海景与夜景',
    recommendedDurationMinutes: 300,
    minimumDurationMinutes: 210,
    districts: ['shinan'],
    placeIds: ['yanerdao', 'aofan', 'mayfourth'],
    suitableFor: ['情侣', '低体力', '夜景'],
    fitnessIntensity: 'low',
    recommendedWindows: [{ start: '15:30', end: '21:00' }],
    openingConstraints: ['海上项目班次属于动态信息，必须由运行时 Provider 或官方渠道确认。'],
    weatherConstraints: ['强风、雷雨时不安排海上项目。'],
    reservationIds: [],
    transportModes: ['walking', 'transit'],
    mealNotes: '晚餐时间由 Planner 保留，具体餐厅不在模块中承诺营业状态。',
    restNotes: '沿海步道可按体力缩短。',
    planBModuleIds: ['module-rainy-indoor'],
    sourceRefIds: [SOURCE],
    splittableInto: [],
    mergeableWith: [],
    conflictsWith: [],
    rationale: '将相邻东岸点位组合为可拆改模块，避免固定日程。',
  }),
  module({
    id: 'module-rainy-indoor',
    name: '雨天室内替代',
    recommendedDurationMinutes: 240,
    minimumDurationMinutes: 180,
    districts: ['shibei', 'shinan'],
    placeIds: ['beer', 'underwater', 'naval'],
    suitableFor: ['雨天', '亲子', '低体力'],
    fitnessIntensity: 'low',
    recommendedWindows: [{ start: '09:00', end: '17:30' }],
    openingConstraints: ['博物馆开放与预约规则必须在出行前复核。'],
    weatherConstraints: [],
    reservationIds: [],
    transportModes: ['transit', 'taxi'],
    mealNotes: '不绑定动态营业餐厅。',
    restNotes: '馆际移动间保留休息。',
    planBModuleIds: [],
    sourceRefIds: [SOURCE],
    splittableInto: [],
    mergeableWith: [],
    conflictsWith: [],
    rationale: '仅使用现有 Legacy 室内点位提供天气替代组合。',
  }),
  module({
    id: 'module-west-coast-sunset',
    name: '黄岛海岸与日落',
    recommendedDurationMinutes: 480,
    minimumDurationMinutes: 360,
    districts: ['west-coast'],
    placeIds: ['golden', 'yumingzui'],
    suitableFor: ['日落', '摄影', '深度旅行'],
    fitnessIntensity: 'medium',
    recommendedWindows: [{ start: '11:00', end: '20:30' }],
    openingConstraints: ['跨湾交通与活动开放属于动态信息，需临近日期确认。'],
    weatherConstraints: ['能见度差或大风时切换市区模块。'],
    reservationIds: [],
    transportModes: ['transit', 'taxi'],
    mealNotes: '不承诺海鲜市场实时营业和价格。',
    restNotes: '跨区日建议安排午休。',
    planBModuleIds: ['module-rainy-indoor'],
    sourceRefIds: [SOURCE],
    splittableInto: [],
    mergeableWith: [],
    conflictsWith: [],
    rationale: '保留 Legacy 黄岛点位组合，具体交通仍等待真实路线 Provider。',
  }),
];
