/* v2.3 behavior-equivalent extraction: booking panel. Generated once, then maintained as canonical source. */
function bookingById(id){return BOOKINGS.find(b=>b.id===id)}
function bookingItemsForPoint(id){return BOOKINGS.filter(b=>b.pointIds.includes(id))}
function bookingItemsForDay(date){return BOOKINGS.filter(b=>b.dates.includes(date))}
function bookingLevelRank(level){return level==='required'?2:level==='suggested'?1:0}
function activeBookingItems(items){return items.filter(b=>progressValue(b.id)!=='abandoned')}
function pointBookingLevel(id){return activeBookingItems(bookingItemsForPoint(id)).reduce((a,b)=>bookingLevelRank(b.level)>bookingLevelRank(a)?b.level:a,'none')}
function dayBookingLevel(date){return activeBookingItems(bookingItemsForDay(date)).reduce((a,b)=>bookingLevelRank(b.level)>bookingLevelRank(a)?b.level:a,'none')}
function progressValue(id){return bookingProgress[id]||'pending'}
function dateLabel(dates){return dates.map(d=>`8月${Number(d.slice(3))}日`).join(' / ')}
function dotHtml(level,id=''){if(level==='none')return'';if(id&&progressValue(id)==='abandoned')return'';const done=id&&['booked','checked'].includes(progressValue(id));return `<span class="booking-dot ${level} ${done?'done':''}" title="${level==='required'?'必须预约/购票':'建议提前'}"></span>`}
function progressSelectHtml(item){const v=progressValue(item.id);return `<select class="booking-progress" data-booking-progress="${item.id}" aria-label="${escapeHtml(item.name)}处理状态"><option value="pending" ${v==='pending'?'selected':''}>未处理</option><option value="booked" ${v==='booked'?'selected':''}>已预约/购票</option><option value="checked" ${v==='checked'?'selected':''}>已核验</option><option value="abandoned" ${v==='abandoned'?'selected':''}>放弃</option></select>`}
function channelButtonsHtml(item){return item.channels.map((c,i)=>`<button class="booking-channel" data-booking-channel="${item.id}" data-channel-index="${i}">${escapeHtml(c.label)}</button>`).join('')}
function bookingItemHtml(item,compact=false){const v=progressValue(item.id),done=['booked','checked'].includes(v),abandoned=v==='abandoned';return `<div class="booking-item ${done?'done':''} ${abandoned?'abandoned':''}"><div class="booking-item-head">${dotHtml(item.level,item.id)}<div class="booking-item-main"><div class="booking-item-title">${escapeHtml(item.name)}${item.optional?'<span class="booking-optional">备选启用后</span>':''}${abandoned?'<span class="booking-abandoned-tag">已放弃</span>':''}</div><div class="booking-item-meta">${dateLabel(item.dates)} · ${abandoned?'不再提醒':item.level==='required'?'必须预约/购票':'建议提前处理'}</div></div></div>${compact?'':`<div class="booking-item-note">${escapeHtml(item.note)}</div>`}<div class="booking-controls">${channelButtonsHtml(item)}${progressSelectHtml(item)}</div></div>`}
function renderBookingChecklist(){const box=document.getElementById('bookingChecklist');const sorted=[...BOOKINGS].sort((a,b)=>bookingLevelRank(b.level)-bookingLevelRank(a.level)||a.dates[0].localeCompare(b.dates[0]));box.innerHTML=`<div class="booking-list">${sorted.map(x=>bookingItemHtml(x)).join('')}</div>`}
function showGuide(message){const box=document.getElementById('guideToast');box.innerHTML=`${escapeHtml(message)}<br><button type="button" id="closeGuide">知道了</button>`;box.classList.add('show');document.getElementById('closeGuide').onclick=()=>box.classList.remove('show');setTimeout(()=>box.classList.remove('show'),6000)}
function platformUrl(kind,keyword){const q=encodeURIComponent(keyword);if(kind==='meituan')return`https://www.meituan.com/s/${q}/`;if(kind==='douyin')return`https://www.douyin.com/search/${q}?type=general`;if(kind==='xhs')return`https://www.xiaohongshu.com/search_result?keyword=${q}`;if(kind==='dianping')return`https://m.dianping.com/search?keyword=${q}`;return''}
function openBookingChannel(id,index){const item=bookingById(id),c=item&&item.channels[index];if(!c)return;if(c.kind==='url'){window.open(c.url,'_blank','noopener');return}if(c.kind==='wechat'){showGuide(`请在微信搜索“${c.keyword}”，从官方公众号/小程序进入。手机将尝试打开微信。`);if(/Android|iPhone|iPad|iPod/i.test(navigator.userAgent))setTimeout(()=>{location.href='weixin://'},150);return}const url=platformUrl(c.kind,c.keyword);if(url)window.open(url,'_blank','noopener')}
function setBookingProgress(id,value){bookingProgress[id]=value;saveJSON(STORAGE_KEY,bookingProgress);refreshLinkedViews()}
function dayBookingsHtml(d){const items=bookingItemsForDay(d.date);return items.length?`<div class="day-bookings"><div class="day-bookings-title">预约 / 购票</div><div class="booking-list">${items.map(x=>bookingItemHtml(x)).join('')}</div></div>`:''}
function pointBookingsSection(p){const items=bookingItemsForPoint(p.id);return items.length?`<div class="search-bookings"><div class="day-bookings-title">预约 / 购票</div>${items.map(x=>bookingItemHtml(x)).join('')}</div>`:''}
