/* v2.5.2 compact girlfriend wishlist with verified map anchors and persistent completion state. */
(function(){
  'use strict';
  const data=window.GIRLFRIEND_WISHLIST||GIRLFRIEND_WISHLIST,storage=window.TravelVersionedStorage,KEY='trip-girlfriend-wishlist-v2.5.1',OLD_KEY='girlfriend-wishlist-progress-v2.5.1';
  let panel=null,filter='food',onlyPending=false,bound=false;
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  function migrate(){try{if(localStorage.getItem(KEY)!==null)return;const old=localStorage.getItem(OLD_KEY);if(old!==null){localStorage.setItem(KEY,old);localStorage.removeItem(OLD_KEY)}}catch{}}
  function read(){migrate();return storage?storage.read(KEY,{}, {schemaVersion:1,migrate:value=>value?.data||value||{}}).data:(()=>{try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return{}}})()}
  function write(value){if(storage)storage.write(KEY,value,{schemaVersion:1});else try{localStorage.setItem(KEY,JSON.stringify(value))}catch{}document.dispatchEvent(new CustomEvent('travel:wishlist-change',{detail:{value}}))}
  function done(id){return Boolean(read()[id])}
  function setDone(id,value){const state=read();if(value)state[id]={done:true,at:new Date().toISOString()};else delete state[id];write(state);render()}
  function dateValue(item,type){return type==='attraction'?item.date:item.suggestedDate}
  function dateLabel(date){return date?`8月${Number(date.slice(3))}日`:'未固定日期'}
  function attractionStatus(item){return item.coverage==='conditional'?'条件项目':`正式行程 · ${dateLabel(item.date)}`}
  function foodStatus(item){const map={must:'必吃/必买',wanted:'想吃备选'};return `${map[item.priority]||'已收录'} · ${dateLabel(item.suggestedDate)}`}
  function pointFor(item){return item.pointId?pointById(item.pointId):null}
  function mapAction(item){if(item.pointId)return `<button type="button" data-wishlist-focus="${esc(item.pointId)}">地图定位</button>`;if(item.mapUrl)return `<a href="${esc(item.mapUrl)}" target="_blank" rel="noopener">地图核对</a>`;return''}
  function aliases(item){const list=[...(item.aliases||[])];if(item.original&&item.original!==item.name)list.unshift(item.original);return list.length?`<small>原话/别名：${list.map(esc).join('、')}</small>`:''}
  function locationBadge(item,type){if(type!=='food')return'';const point=pointFor(item);if(!point)return'<span class="wishlist-location-badge anchor">位置待补</span>';const exact=['exact','address'].includes(point.precision);return `<span class="wishlist-location-badge ${exact?'':'anchor'}">${exact?'真实门店/地址':'真实核验点'} · ${esc(point.mapLabel||point.name)}</span>`}
  function itemHtml(item,type){const checked=done(item.id),status=type==='attraction'?attractionStatus(item):foodStatus(item);return `<article class="wishlist-item ${checked?'done':''}" data-wishlist-type="${type}" data-wishlist-id="${esc(item.id)}"><label class="wishlist-check"><input type="checkbox" data-wishlist-done="${esc(item.id)}" ${checked?'checked':''} aria-label="标记${esc(item.name)}完成"><span aria-hidden="true"></span></label><div class="wishlist-main"><div class="wishlist-name"><b>${esc(item.name)}</b>${item.target?`<em>${esc(item.target)}</em>`:''}</div>${aliases(item)}<div class="wishlist-status">${esc(status)}${item.suggestedMoment?` · ${esc(item.suggestedMoment)}`:''}</div>${locationBadge(item,type)}<details class="wishlist-item-details"><summary>查看地址与提醒</summary>${item.address?`<small>${esc(item.address)}</small>`:''}${item.note?`<p>${esc(item.note)}</p>`:''}</details></div><div class="wishlist-actions">${mapAction(item)}${item.sourceUrl?`<a href="${esc(item.sourceUrl)}" target="_blank" rel="noopener">来源</a>`:''}</div></article>`}
  function coverage(){const routeIds=new Set((SCHEDULES||[]).flatMap(day=>day.route||[])),scheduleText=(SCHEDULES||[]).map(day=>JSON.stringify(day)).join(' '),attractions=data.attractions.map(item=>({id:item.id,covered:item.coverage==='conditional'?routeIds.has(item.pointId)||scheduleText.includes(item.name)||(item.aliases||[]).some(alias=>scheduleText.includes(alias)):routeIds.has(item.pointId)})),foods=data.food.map(item=>({id:item.id,tracked:Boolean(item.mapPointId&&pointById(item.mapPointId))}));return{attractions,totalAttractions:attractions.length,coveredAttractions:attractions.filter(item=>item.covered).length,foods,totalFoods:foods.length,mappedFoods:foods.filter(item=>item.tracked).length,completed:Object.keys(read()).length}}
  function summaryHtml(){const state=coverage();return `<div class="wishlist-summary"><span><b>${state.coveredAttractions}/${state.totalAttractions}</b> 必去景点覆盖</span><span><b>${state.mappedFoods}/${state.totalFoods}</b> 必吃必买已关联地图</span><span><b>${state.completed}</b> 项已完成</span></div>`}
  function filtered(){const attractions=data.attractions.map(item=>({item,type:'attraction'})),food=data.food.map(item=>({item,type:'food'}));return[...attractions,...food].filter(entry=>(filter==='all'||filter===entry.type)&&(!onlyPending||!done(entry.item.id)))}
  function groupedHtml(){const groups=new Map();for(const entry of filtered()){const date=dateValue(entry.item,entry.type)||'other';if(!groups.has(date))groups.set(date,[]);groups.get(date).push(entry)}return[...groups.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([date,entries])=>`<section class="wishlist-day-group"><div class="wishlist-day-group-title"><b>${dateLabel(date==='other'?'':date)}</b><span>${entries.length}项</span></div>${entries.map(entry=>itemHtml(entry.item,entry.type)).join('')}</section>`).join('')||'<p class="wishlist-empty">当前筛选下已全部完成。</p>'}
  function mapToolbar(){const mode=window.TravelWishlistMap?.mode?.()||'day';return `<div class="wishlist-map-toolbar"><strong>地图显示</strong><button type="button" data-wishlist-map-mode="day" class="${mode==='day'?'active':''}">仅当天</button><button type="button" data-wishlist-map-mode="all" class="${mode==='all'?'active':''}">全部点位</button><button type="button" data-wishlist-map-mode="off" class="${mode==='off'?'active':''}">隐藏</button></div>`}
  function panelHtml(){return `<div class="trip-tool-head wishlist-head"><div><b>${esc(data.title)}</b><span>固定门店与真实核验点分开标注，不把动态供应伪装成已确认有货。</span></div><button type="button" data-wishlist-reset>重置完成状态</button></div>${summaryHtml()}<div class="wishlist-toolbar" role="group" aria-label="清单筛选"><button type="button" data-wishlist-filter="food" class="${filter==='food'?'active':''}">必吃必买</button><button type="button" data-wishlist-filter="attraction" class="${filter==='attraction'?'active':''}">必去景点</button><button type="button" data-wishlist-filter="all" class="${filter==='all'?'active':''}">全部</button><label><input type="checkbox" data-wishlist-pending ${onlyPending?'checked':''}> 只看未完成</label></div>${mapToolbar()}<div class="wishlist-list">${groupedHtml()}</div><div class="wishlist-seafood-rule"><b>${esc(data.seafoodRule.title)}</b><p>${esc(data.seafoodRule.text)}</p></div>`}
  function ensure(){if(panel&&panel.isConnected)return panel;const root=document.getElementById('tripToolsRoot');if(!root)return null;panel=document.createElement('section');panel.id='girlfriendWishlistPanel';panel.className='trip-tool-card wide girlfriend-wishlist-card';const body=root.querySelector('[data-tool-body="wishlist"]'),anchor=root.querySelector('#nextStopPanel');if(body)body.appendChild(panel);else if(anchor)anchor.insertAdjacentElement('afterend',panel);else root.prepend(panel);bind();return panel}
  function syncVersionBadge(){document.querySelectorAll('#dataStatusContent .data-badge').forEach(node=>{if(node.textContent.includes('按需加载 · v'))node.textContent=`按需加载 · v${typeof APP_VERSION==='string'?APP_VERSION:'2.5.2'}`})}
  function render(){const node=ensure();if(!node)return;node.innerHTML=panelHtml();renderDailyHint();syncVersionBadge();window.TravelTripToolsLayout?.apply?.()}
  function renderDailyHint(){const box=document.getElementById('dailyCardContent'),date=TravelStore?.state?.toolsDay||TravelStore?.state?.selectedDay;if(!box||!date)return;box.querySelector('.wishlist-day-hint')?.remove();const items=data.food.filter(item=>item.suggestedDate===date);if(!items.length)return;const card=box.querySelector('.concise-day-card')||box;card.insertAdjacentHTML('beforeend',`<div class="wishlist-day-hint"><b>她想吃/买：</b>${items.map(item=>`${esc(item.name)}${item.target?'（'+esc(item.target)+'）':''}`).join('、')}</div>`)}
  function focusMapped(id){window.TravelWishlistMap?.ensureVisible?.(id);requestAnimationFrame(()=>setTimeout(()=>{if(typeof focusPoint==='function')focusPoint(id)},40))}
  function bind(){if(bound)return;bound=true;document.addEventListener('change',event=>{const checkbox=event.target.closest('[data-wishlist-done]');if(checkbox){setDone(checkbox.dataset.wishlistDone,checkbox.checked);return}const pending=event.target.closest('[data-wishlist-pending]');if(pending){onlyPending=pending.checked;render()}});document.addEventListener('click',event=>{const focus=event.target.closest('[data-wishlist-focus]');if(focus){focusMapped(focus.dataset.wishlistFocus);return}const filterButton=event.target.closest('[data-wishlist-filter]');if(filterButton){filter=filterButton.dataset.wishlistFilter;render();return}const mapMode=event.target.closest('[data-wishlist-map-mode]');if(mapMode){window.TravelWishlistMap?.setMode?.(mapMode.dataset.wishlistMapMode);render();return}if(event.target.closest('[data-wishlist-reset]')){if(confirm('清除“她想去/想吃清单”的本机完成状态？')){write({});render()}}});TravelStore?.subscribe?.(change=>{if(change.changed?.selectedDay||change.changed?.toolsDay)queueMicrotask(()=>{renderDailyHint();if(window.TravelWishlistMap?.mode?.()==='day')window.TravelWishlistMap.setMode('day')})});document.addEventListener('travel:wishlist-change',renderDailyHint);document.addEventListener('travel:wishlist-map-mode',()=>queueMicrotask(render))}
  function install(){const operations=window.TravelTripOperations;if(!operations)return;const originalInit=operations.init,originalRenderAll=operations.renderAll;if(originalInit&&!originalInit.__wishlist)operations.init=Object.assign(function(...args){const result=originalInit.apply(this,args);render();return result},{__wishlist:true});if(originalRenderAll&&!originalRenderAll.__wishlist)operations.renderAll=Object.assign(function(...args){const result=originalRenderAll.apply(this,args);render();return result},{__wishlist:true})}
  install();
  window.TravelGirlfriendWishlist=Object.freeze({data,coverage,read,setDone,render,renderDailyHint,syncVersionBadge,key:KEY});
})();
