/* v2.5.1 complete girlfriend wishlist: coverage, execution plan and local completion state. */
(function(){
  'use strict';
  const data=window.GIRLFRIEND_WISHLIST||GIRLFRIEND_WISHLIST,storage=window.TravelVersionedStorage,KEY='girlfriend-wishlist-progress-v2.5.1',wishlistAttractions=data.attractions;
  let panel=null,filter='all',onlyPending=false,bound=false;
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  function read(){return storage?storage.read(KEY,{}, {schemaVersion:1,migrate:value=>value?.data||value||{}}).data:(()=>{try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return{}}})()}
  function write(value){if(storage)storage.write(KEY,value,{schemaVersion:1});else try{localStorage.setItem(KEY,JSON.stringify(value))}catch{}document.dispatchEvent(new CustomEvent('travel:wishlist-change',{detail:{value}}))}
  function done(id){return Boolean(read()[id])}
  function setDone(id,value){const state=read();if(value)state[id]={done:true,at:new Date().toISOString()};else delete state[id];write(state);render()}
  function dateLabel(date){return date?`8月${Number(date.slice(3))}日`:''}
  function attractionStatus(item){return item.coverage==='conditional'?'条件项目':`正式行程 · ${dateLabel(item.date)}`}
  function foodStatus(item){const map={must:'必吃/必买',wanted:'想吃备选'};return `${map[item.priority]||'已收录'} · ${dateLabel(item.suggestedDate)}`}
  function mapAction(item){if(item.pointId)return `<button type="button" data-wishlist-focus="${esc(item.pointId)}">地图定位</button>`;if(item.mapUrl)return `<a href="${esc(item.mapUrl)}" target="_blank" rel="noopener">高德核对</a>`;return''}
  function aliases(item){const list=[...(item.aliases||[])];if(item.original&&item.original!==item.name)list.unshift(item.original);return list.length?`<small>原话/别名：${list.map(esc).join('、')}</small>`:''}
  function itemHtml(item,type){const checked=done(item.id),status=type==='attraction'?attractionStatus(item):foodStatus(item);return `<article class="wishlist-item ${checked?'done':''}" data-wishlist-type="${type}" data-wishlist-id="${esc(item.id)}"><label class="wishlist-check"><input type="checkbox" data-wishlist-done="${esc(item.id)}" ${checked?'checked':''}><span aria-hidden="true"></span></label><div class="wishlist-main"><div class="wishlist-name"><b>${esc(item.name)}</b>${item.target?`<em>${esc(item.target)}</em>`:''}</div>${aliases(item)}<div class="wishlist-status">${esc(status)}${item.suggestedMoment?` · ${esc(item.suggestedMoment)}`:''}</div>${item.address?`<small>${esc(item.address)}</small>`:''}${item.note?`<p>${esc(item.note)}</p>`:''}</div><div class="wishlist-actions">${mapAction(item)}${item.sourceUrl?`<a href="${esc(item.sourceUrl)}" target="_blank" rel="noopener">来源</a>`:''}</div></article>`}
  function coverage(){const routeIds=new Set((SCHEDULES||[]).flatMap(day=>day.route||[])),scheduleText=(SCHEDULES||[]).map(day=>JSON.stringify(day)).join(' '),attractions=wishlistAttractions.map(item=>({id:item.id,covered:item.coverage==='conditional'?routeIds.has(item.pointId)||scheduleText.includes(item.name)||(item.aliases||[]).some(alias=>scheduleText.includes(alias)):routeIds.has(item.pointId)})),foods=data.food.map(item=>({id:item.id,tracked:true}));return{attractions,totalAttractions:attractions.length,coveredAttractions:attractions.filter(item=>item.covered).length,foods,totalFoods:foods.length,completed:Object.keys(read()).length}}
  function summaryHtml(){const state=coverage();return `<div class="wishlist-summary"><span><b>${state.coveredAttractions}/${state.totalAttractions}</b> 个独立景点已覆盖</span><span><b>${state.totalFoods}</b> 项餐饮/饮料/购买任务已收录</span><span><b>${state.completed}</b> 项已完成</span></div>`}
  function filtered(){const attractions=wishlistAttractions.map(item=>({item,type:'attraction'})),food=data.food.map(item=>({item,type:'food'}));return [...attractions,...food].filter(entry=>(filter==='all'||filter===entry.type)&&(!onlyPending||!done(entry.item.id)))}
  function panelHtml(){const entries=filtered();return `<div class="trip-tool-head wishlist-head"><div><b>${esc(data.title)}</b><span>用户原话完整保留，重复名称按同一地点处理</span></div><button type="button" data-wishlist-reset>重置完成状态</button></div>${summaryHtml()}<div class="wishlist-toolbar" role="group" aria-label="清单筛选"><button type="button" data-wishlist-filter="all" class="${filter==='all'?'active':''}">全部</button><button type="button" data-wishlist-filter="attraction" class="${filter==='attraction'?'active':''}">景点</button><button type="button" data-wishlist-filter="food" class="${filter==='food'?'active':''}">餐饮与购买</button><label><input type="checkbox" data-wishlist-pending ${onlyPending?'checked':''}> 只看未完成</label></div><div class="wishlist-list">${entries.map(entry=>itemHtml(entry.item,entry.type)).join('')||'<p class="wishlist-empty">当前筛选下已全部完成。</p>'}</div><div class="wishlist-seafood-rule"><b>${esc(data.seafoodRule.title)}</b><p>${esc(data.seafoodRule.text)}</p></div>`}
  function ensure(){if(panel&&panel.isConnected)return panel;const root=document.getElementById('tripToolsRoot');if(!root)return null;panel=document.createElement('section');panel.id='girlfriendWishlistPanel';panel.className='trip-tool-card wide girlfriend-wishlist-card';const anchor=root.querySelector('#nextStopPanel');if(anchor)anchor.insertAdjacentElement('afterend',panel);else root.prepend(panel);bind();return panel}
  function syncVersionBadge(){document.querySelectorAll('#dataStatusContent .data-badge').forEach(node=>{if(node.textContent.includes('按需加载 · v'))node.textContent=`按需加载 · v${typeof APP_VERSION==='string'?APP_VERSION:'2.5.1'}`})}
  function render(){const node=ensure();if(!node)return;node.innerHTML=panelHtml();renderDailyHint();syncVersionBadge()}
  function renderDailyHint(){const box=document.getElementById('dailyCardContent'),date=TravelStore?.state?.toolsDay||TravelStore?.state?.selectedDay;if(!box||!date)return;box.querySelector('.wishlist-day-hint')?.remove();const items=data.food.filter(item=>item.suggestedDate===date);if(!items.length)return;const card=box.querySelector('.concise-day-card')||box;card.insertAdjacentHTML('beforeend',`<div class="wishlist-day-hint"><b>她想吃/买：</b>${items.map(item=>`${esc(item.name)}${item.target?'（'+esc(item.target)+'）':''}`).join('、')}</div>`)}
  function bind(){if(bound)return;bound=true;document.addEventListener('change',event=>{const checkbox=event.target.closest('[data-wishlist-done]');if(checkbox){setDone(checkbox.dataset.wishlistDone,checkbox.checked);return}const pending=event.target.closest('[data-wishlist-pending]');if(pending){onlyPending=pending.checked;render()}});document.addEventListener('click',event=>{const focus=event.target.closest('[data-wishlist-focus]');if(focus){focusPoint(focus.dataset.wishlistFocus);return}const filterButton=event.target.closest('[data-wishlist-filter]');if(filterButton){filter=filterButton.dataset.wishlistFilter;render();return}if(event.target.closest('[data-wishlist-reset]')){if(confirm('清除“她想去/想吃清单”的本机完成状态？')){write({});render()}}});TravelStore?.subscribe?.(change=>{if(change.changed?.selectedDay||change.changed?.toolsDay)queueMicrotask(renderDailyHint)});document.addEventListener('travel:wishlist-change',renderDailyHint)}
  function install(){const operations=window.TravelTripOperations;if(!operations)return;const originalInit=operations.init,originalRenderAll=operations.renderAll;if(originalInit&&!originalInit.__wishlist)operations.init=Object.assign(function(...args){const result=originalInit.apply(this,args);render();return result},{__wishlist:true});if(originalRenderAll&&!originalRenderAll.__wishlist)operations.renderAll=Object.assign(function(...args){const result=originalRenderAll.apply(this,args);render();return result},{__wishlist:true})}
  install();
  window.TravelGirlfriendWishlist=Object.freeze({data,wishlistAttractions,coverage,read,setDone,render,renderDailyHint,syncVersionBadge,key:KEY});
})();
