(()=>{
'use strict';
const data=window.QINGDAO_RAIN_COMPAT_DATA;
const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const link=(url,label='查看来源')=>url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`:'';
function newItems(){return `<h2>新增到旧版线的地点与体验</h2><div class="rain-grid">${data.newItems.map(item=>`<article class="rain-card"><span>${esc(item.tag)}</span><h3>${esc(item.name)}</h3><p>${esc(item.detail)}</p>${link(item.url)}</article>`).join('')}</div>`}
function recommended(){return `<h2>雨天可去 / 条件可去</h2><div class="rain-grid">${data.recommended.map(item=>`<article class="rain-card"><span>${esc(item[1])}</span><h3>${esc(item[0])}</h3><p>${esc(item[2])}</p>${link(item[3])}</article>`).join('')}</div><div class="source-note">雨天经验来自你上传的抖音截图；这里没有把短视频内容直接当成官方事实。崂山、浴场、海上项目等高风险户外地点始终以天气预警和官方关闭通知为准。</div>`}
function avoid(){return `<h2>雨天避坑 / 强制取消</h2><div class="rain-list">${data.avoid.map(item=>`<article class="rain-card avoid"><h3>${esc(item[0])}</h3><p>${esc(item[1])}</p></article>`).join('')}</div>`}
function beaches(){return `<h2>9处海水浴场 · 服务时段与封海核验</h2><div class="rain-table-wrap"><table class="rain-table"><thead><tr><th>浴场</th><th>开放季</th><th>本次行程服务时间</th><th>即时状态</th><th>咨询电话</th></tr></thead><tbody>${data.beaches.map(item=>`<tr><td><b>${esc(item[0])}</b></td><td>${esc(item[1])}</td><td>${esc(item[2])}</td><td><span class="status-unknown">需当日复核</span><br><small>本次检索未发现8/8临时封海官方公告；不等于确认开放</small></td><td><a href="tel:${esc(item[3].replace(/-/g,''))}">${esc(item[3])}</a></td></tr>`).join('')}</tbody></table></div><div class="source-note"><b>官方规则：</b>浴场关闭时切勿下海；天气突变或听到撤离指令立即上岸。${link(data.beachSource,'2026浴场官方公示')} ${link(data.weatherSource,'青岛气象灾害应急预案')}</div>`}
function food(){return `<h2>餐饮与海上项目避坑</h2><ul class="food-list">${data.foodRules.map(item=>`<li>${esc(item)}</li>`).join('')}</ul><div class="source-note">私人游艇、“青岛大虾”、白花蛇草水等判断保留为你的个人体验/偏好，不包装成全体游客的客观定论。</div>`}
function sources(){return `<h2>资料边界</h2><div class="rain-list"><article class="rain-card"><h3>官方来源</h3><p>用于浴场开放服务时段、气象安全规则和室内场馆营业信息。</p>${link(data.beachSource,'浴场官方公示')} ${link(data.weatherSource,'气象应急预案')}</article><article class="rain-card"><h3>你上传的雨天截图</h3><p>用于“什么天气下体验好/差”的社交平台经验线索；截图中对北九水、浴场等内容一律增加安全门槛。</p>${data.socialSources.map((url,index)=>link(url,`抖音参考${index+1}`)).join(' ')}</article></div>`}
const panes={new:newItems,recommend:recommended,avoid,beaches,food,sources};
function render(){const root=document.getElementById('rainBody');if(root)root.innerHTML=panes.new()}
function setOpen(open){const drawer=document.getElementById('rainDrawer'),button=document.getElementById('rainToggle');if(!drawer||!button)return;drawer.hidden=!open;button.setAttribute('aria-expanded',String(open));if(open)drawer.querySelector('button')?.focus()}
function setPane(name){document.querySelectorAll('[data-rain-tab]').forEach(btn=>btn.classList.toggle('active',btn.dataset.rainTab===name));const root=document.getElementById('rainBody');if(root&&panes[name])root.innerHTML=panes[name]()}
window.addEventListener('DOMContentLoaded',()=>{render();document.getElementById('rainToggle')?.addEventListener('click',()=>setOpen(document.getElementById('rainDrawer')?.hidden!==false));document.getElementById('rainClose')?.addEventListener('click',()=>setOpen(false));document.querySelectorAll('[data-rain-tab]').forEach(btn=>btn.addEventListener('click',()=>setPane(btn.dataset.rainTab)));document.addEventListener('keydown',event=>{if(event.key==='Escape')setOpen(false)})});
})();
