/* v2.3 behavior-equivalent extraction: AMap real marker and route renderer. Generated once, then maintained as canonical source. */
function clearAmapOverlays(){if(!amapInstance)return;if(amapMarkerCluster){try{amapMarkerCluster.setData([])}catch(e){}try{if(typeof amapMarkerCluster.setMap==='function')amapMarkerCluster.setMap(null)}catch(e){}amapMarkerCluster=null}if(amapInfoWindow)try{amapInfoWindow.close()}catch(e){};[...amapMarkers,...amapOverlays].forEach(item=>{try{amapInstance.remove(item)}catch(e){}});amapMarkers=[];amapOverlays=[];amapClusterPointMap=new Map()}
function amapPointPosition(p){const [lat,lng]=wgs84ToGcj02(p.lat,p.lng);return[lng,lat]}
function amapRenderTravelView(){if(!amapInstance||!window.AMap)return;clearAmapOverlays();const ps=visiblePoints(selectedDay),data=ps.map(p=>{const lnglat=amapPointPosition(p);amapClusterPointMap.set(amapMarkerPositionKey(lnglat),p);return{lnglat,weight:['住宿区域','酒店'].includes(p.category)?5:1,id:p.id}});if(data.length)amapMarkerCluster=new AMap.MarkerCluster(amapInstance,data,{gridSize:38,maxZoom:16,averageCenter:true,clusterByZoomChange:true,renderClusterMarker:amapRenderClusterBadge,renderMarker:amapRenderClusterPoint});if(routeVisible){const days=selectedDay?SCHEDULES.filter(d=>d.date===selectedDay):SCHEDULES.slice(1);days.forEach(d=>{const points=routePoints(d),path=points.map(amapPointPosition);if(path.length<2)return;if(!selectedDay){amapOverlays.push(new AMap.Polyline({path,strokeColor:'#fff',strokeWeight:5,strokeOpacity:.65,lineJoin:'round',zIndex:40}),new AMap.Polyline({path,strokeColor:d.color,strokeWeight:3,strokeOpacity:.58,strokeStyle:'dashed',strokeDasharray:[5,8],lineJoin:'round',zIndex:41}));return}amapOverlays.push(new AMap.Polyline({path,strokeColor:'#fff',strokeWeight:11,strokeOpacity:.94,lineCap:'round',lineJoin:'round',zIndex:45}),new AMap.Polyline({path,strokeColor:d.color,strokeWeight:6,strokeOpacity:1,lineCap:'round',lineJoin:'round',zIndex:46}));const order=routeOrderMap(d);order.forEach((nums,id)=>{const p=pointById(id);if(!p)return;const marker=new AMap.Marker({position:amapPointPosition(p),content:`<div class="amap-route-marker">${travelRouteMarkerHtml(d.color,nums.join('/'),p)}</div>`,offset:new AMap.Pixel(-15,-17),zIndex:700,extData:id,title:p.name});marker.on('click',()=>amapOpenPoint(marker.getExtData()));amapOverlays.push(marker)});for(let i=0;i<path.length-1;i++){const a=path[i],b=path[i+1],count=amapDistanceMeters(a,b)>18000?2:1,rotation=Math.atan2(b[1]-a[1],b[0]-a[0])*180/Math.PI;for(let k=1;k<=count;k++){const ratio=count===1?.5:k/(count+1),position=[a[0]+(b[0]-a[0])*ratio,a[1]+(b[1]-a[1])*ratio];amapOverlays.push(new AMap.Marker({position,content:`<div class="amap-direction-marker">${travelDirectionHtml(d.color,rotation)}</div>`,offset:new AMap.Pixel(-14,-14),zIndex:600}))}}})}if(amapOverlays.length)amapInstance.add(amapOverlays);const fit=selectedDay?routePoints(SCHEDULES.find(x=>x.date===selectedDay)):ps;amapFitTravelPoints(fit,selectedDay?15:11)}
function amapSyncTravelView(){if(mapEngine==='amap'&&amapInstance)renderAmapView()}
function amapMarkerPositionKey(value){const loc=amapPoiLocation(value);return loc?loc.map(v=>Number(v).toFixed(6)).join(','):''}
function amapOpenPoint(id){const p=pointById(id);if(!p||!amapInstance)return;const position=amapPointPosition(p);amapInstance.setZoomAndCenter(16,position);if(amapInfoWindow)try{amapInfoWindow.close()}catch(e){};amapInfoWindow=new AMap.InfoWindow({content:popup(p),offset:new AMap.Pixel(58,-18),closeWhenClickMap:true});amapInfoWindow.open(amapInstance,position)}
function amapRenderClusterPoint(context){const marker=context.marker,p=amapFindClusterPoint(marker.getPosition());if(!p)return;marker.setContent(`<div class="amap-travel-marker">${travelMarkerHtml(p)}</div>`);marker.setOffset(new AMap.Pixel(-15,-16));marker.setTitle(p.name);marker.setExtData(p.id);if(!marker.__travelPointBound){marker.on('click',()=>amapOpenPoint(marker.getExtData()));marker.__travelPointBound=true}}
function amapRenderClusterBadge(context){const count=context.count,size=Math.min(48,30+Math.round(Math.log2(Math.max(2,count))*4));context.marker.setContent(`<div class="amap-cluster-badge" style="width:${size}px;height:${size}px">${count}</div>`);context.marker.setOffset(new AMap.Pixel(-size/2,-size/2))}
function amapDistanceMeters(a,b){const rad=Math.PI/180,lat1=a[1]*rad,lat2=b[1]*rad,dLat=(b[1]-a[1])*rad,dLng=(b[0]-a[0])*rad,x=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;return 6371000*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function amapFitTravelPoints(points,maxZoom=12){if(!amapInstance||!points?.length)return;const positions=points.map(amapPointPosition);if(positions.length===1){amapInstance.setZoomAndCenter(maxZoom,positions[0]);return}let minLng=Infinity,minLat=Infinity,maxLng=-Infinity,maxLat=-Infinity;positions.forEach(([lng,lat])=>{minLng=Math.min(minLng,lng);minLat=Math.min(minLat,lat);maxLng=Math.max(maxLng,lng);maxLat=Math.max(maxLat,lat)});const bounds=new AMap.Bounds([minLng,minLat],[maxLng,maxLat]),avoid=innerWidth<=800?[150,210,52,52]:[82,82,82,82];const fit=amapInstance.getFitZoomAndCenterByBounds(bounds,avoid,maxZoom);if(fit?.length===2)amapInstance.setZoomAndCenter(fit[0],fit[1]);else amapInstance.setBounds(bounds,false,avoid)}
(function(){const adapter={id:'amap',ready:()=>typeof amapInstance!=='undefined'&&Boolean(amapInstance),resize:()=>{try{amapInstance?.resize()}catch{}},view:()=>{try{const c=amapInstance.getCenter();return{center:[c.lng,c.lat],zoom:amapInstance.getZoom()}}catch{return null}},setView:view=>{try{if(view?.center)amapInstance.setZoomAndCenter(view.zoom,view.center,true)}catch{}},renderMarkers:()=>amapRenderTravelView(),renderRoute:()=>amapRenderTravelView(),renderAll:()=>amapRenderTravelView(),fitPoints:(points,maxZoom)=>amapFitTravelPoints(points,maxZoom),clearLayer:name=>{if(name==='tripRoutes'||name==='tripMarkers')clearAmapOverlays();if(name==='serviceSelection'&&window.TravelCore)window.TravelCore.overlays.clear('serviceSelection',amapInstance)}};window.TravelAmapAdapter=adapter})();
