/* v2.4 explicit-context AMap adapter. */
(function(){
  function createAmapTravelAdapter(ctx){
    const api=()=>ctx.AMap();
    function pointPosition(point){const converted=ctx.coordinate.wgs84ToGcj02(point.lat,point.lng);return[converted[1],converted[0]]}
    function markerPositionKey(value){const location=ctx.poiLocation(value);return location?location.map(v=>Number(v).toFixed(6)).join(','):''}
    function distanceMeters(a,b){const rad=Math.PI/180,lat1=a[1]*rad,lat2=b[1]*rad,dLat=(b[1]-a[1])*rad,dLng=(b[0]-a[0])*rad,x=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;return 6371000*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
    function clearOverlays(){const map=ctx.amap.instance;if(!map)return;const cluster=ctx.amap.markerCluster;if(cluster){try{cluster.setData([])}catch{}try{cluster.setMap?.(null)}catch{}ctx.amap.markerCluster=null}try{ctx.amap.infoWindow?.close()}catch{};[...(ctx.amap.markers||[]),...(ctx.amap.overlays||[])].forEach(item=>{try{map.remove(item)}catch{}});ctx.amap.markers=[];ctx.amap.overlays=[];ctx.amap.clusterPointMap=new Map()}
    function findClusterPoint(position){const key=markerPositionKey(position),map=ctx.amap.clusterPointMap;if(map?.has(key))return map.get(key);const location=ctx.poiLocation(position);return ctx.visiblePoints(ctx.state.selectedDay).find(point=>{const p=pointPosition(point);return Math.abs(p[0]-location[0])<.00002&&Math.abs(p[1]-location[1])<.00002})||null}
    function openPoint(id){const point=ctx.pointById(id),map=ctx.amap.instance,A=api();if(!point||!map||!A)return;const position=pointPosition(point);map.setZoomAndCenter(16,position);try{ctx.amap.infoWindow?.close()}catch{}ctx.amap.infoWindow=new A.InfoWindow({content:ctx.popup(point),offset:new A.Pixel(58,-18),closeWhenClickMap:true});ctx.amap.infoWindow.open(map,position)}
    function renderClusterPoint(context){const A=api(),marker=context.marker,point=findClusterPoint(marker.getPosition());if(!point||!A)return;marker.setContent('<div class="amap-travel-marker">'+ctx.renderModel.markerHtml(point)+'</div>');marker.setOffset(new A.Pixel(-15,-16));marker.setTitle(point.name);marker.setExtData(point.id);if(!marker.__travelPointBound){marker.on('click',()=>openPoint(marker.getExtData()));marker.__travelPointBound=true}}
    function renderClusterBadge(context){const A=api(),count=context.count,size=Math.min(48,30+Math.round(Math.log2(Math.max(2,count))*4));context.marker.setContent('<div class="amap-cluster-badge" style="width:'+size+'px;height:'+size+'px">'+count+'</div>');context.marker.setOffset(new A.Pixel(-size/2,-size/2))}
    function fitPoints(points,maxZoom=12){const map=ctx.amap.instance,A=api();if(!map||!A||!points?.length)return;const positions=points.map(pointPosition);if(positions.length===1){map.setZoomAndCenter(maxZoom,positions[0]);return}let minLng=Infinity,minLat=Infinity,maxLng=-Infinity,maxLat=-Infinity;positions.forEach(([lng,lat])=>{minLng=Math.min(minLng,lng);minLat=Math.min(minLat,lat);maxLng=Math.max(maxLng,lng);maxLat=Math.max(maxLat,lat)});const bounds=new A.Bounds([minLng,minLat],[maxLng,maxLat]),avoid=innerWidth<=800?[150,210,52,52]:[82,82,82,82],fit=map.getFitZoomAndCenterByBounds(bounds,avoid,maxZoom);if(fit?.length===2)map.setZoomAndCenter(fit[0],fit[1]);else map.setBounds(bounds,false,avoid)}
    function renderAll(){const map=ctx.amap.instance,A=api();if(!map||!A)return;clearOverlays();const points=ctx.visiblePoints(ctx.state.selectedDay),data=points.map(point=>{const lnglat=pointPosition(point);ctx.amap.clusterPointMap.set(markerPositionKey(lnglat),point);return{lnglat,weight:['住宿区域','酒店'].includes(point.category)?5:1,id:point.id}});if(data.length)ctx.amap.markerCluster=new A.MarkerCluster(map,data,{gridSize:38,maxZoom:16,averageCenter:true,clusterByZoomChange:true,renderClusterMarker:renderClusterBadge,renderMarker:renderClusterPoint});const overlays=[];if(ctx.state.routeVisible){const days=ctx.state.selectedDay?ctx.schedules().filter(day=>day.date===ctx.state.selectedDay):ctx.schedules().slice(1);days.forEach(day=>{const route=ctx.routePoints(day),path=route.map(pointPosition);if(path.length<2)return;if(!ctx.state.selectedDay){overlays.push(new A.Polyline({path,strokeColor:'#fff',strokeWeight:5,strokeOpacity:.65,lineJoin:'round',zIndex:40}),new A.Polyline({path,strokeColor:day.color,strokeWeight:3,strokeOpacity:.58,strokeStyle:'dashed',strokeDasharray:[5,8],lineJoin:'round',zIndex:41}));return}overlays.push(new A.Polyline({path,strokeColor:'#fff',strokeWeight:11,strokeOpacity:.94,lineCap:'round',lineJoin:'round',zIndex:45}),new A.Polyline({path,strokeColor:day.color,strokeWeight:6,strokeOpacity:1,lineCap:'round',lineJoin:'round',zIndex:46}));ctx.routeOrderMap(day).forEach((numbers,id)=>{const point=ctx.pointById(id);if(!point)return;const marker=new A.Marker({position:pointPosition(point),content:'<div class="amap-route-marker">'+ctx.renderModel.routeMarkerHtml(day.color,numbers.join('/'),point)+'</div>',offset:new A.Pixel(-15,-17),zIndex:700,extData:id,title:point.name});marker.on('click',()=>openPoint(marker.getExtData()));overlays.push(marker)});for(let index=0;index<path.length-1;index++){const a=path[index],b=path[index+1],count=distanceMeters(a,b)>18000?2:1,rotation=Math.atan2(b[1]-a[1],b[0]-a[0])*180/Math.PI;for(let k=1;k<=count;k++){const ratio=count===1?.5:k/(count+1),position=[a[0]+(b[0]-a[0])*ratio,a[1]+(b[1]-a[1])*ratio];overlays.push(new A.Marker({position,content:'<div class="amap-direction-marker">'+ctx.renderModel.directionHtml(day.color,rotation)+'</div>',offset:new A.Pixel(-14,-14),zIndex:600}))}}})}ctx.amap.overlays=overlays;if(overlays.length)map.add(overlays);const fit=ctx.state.selectedDay?ctx.routePoints(ctx.schedules().find(day=>day.date===ctx.state.selectedDay)):points;fitPoints(fit,ctx.state.selectedDay?15:11)}
    return{id:'amap',context:ctx,ready:()=>Boolean(ctx.amap.instance),resize:()=>{try{ctx.amap.instance?.resize()}catch{}},view:()=>{try{const center=ctx.amap.instance.getCenter();return{center:[center.lng,center.lat],zoom:ctx.amap.instance.getZoom()}}catch{return null}},setView:view=>{try{if(view?.center)ctx.amap.instance.setZoomAndCenter(view.zoom,view.center,true)}catch{}},renderMarkers:renderAll,renderRoute:renderAll,renderAll,fitPoints,clearLayer:name=>{if(name==='tripRoutes'||name==='tripMarkers')clearOverlays();if(name==='serviceSelection')ctx.clearServiceSelection?.()},clearOverlays,pointPosition,markerPositionKey,distanceMeters,openPoint,renderClusterPoint,renderClusterBadge};
  }
  window.createAmapTravelAdapter=createAmapTravelAdapter;
  window.TravelAmapAdapter=createAmapTravelAdapter({state:TravelAppContext.state,amap:TravelAppContext.amap,AMap:()=>window.AMap,coordinate:TravelCoordinates,poiLocation:amapPoiLocation,visiblePoints,schedules:()=>SCHEDULES,routePoints,routeOrderMap,pointById,popup,renderModel:TravelRenderModel,clearServiceSelection:()=>window.TravelCore?.overlays.clear('serviceSelection',TravelAppContext.amap.instance)});
  window.clearAmapOverlays=()=>TravelAmapAdapter.clearOverlays();window.amapPointPosition=point=>TravelAmapAdapter.pointPosition(point);window.amapMarkerPositionKey=value=>TravelAmapAdapter.markerPositionKey(value);window.amapOpenPoint=id=>TravelAmapAdapter.openPoint(id);window.amapRenderClusterPoint=context=>TravelAmapAdapter.renderClusterPoint(context);window.amapRenderClusterBadge=context=>TravelAmapAdapter.renderClusterBadge(context);window.amapDistanceMeters=(a,b)=>TravelAmapAdapter.distanceMeters(a,b);window.amapFitTravelPoints=(points,maxZoom)=>TravelAmapAdapter.fitPoints(points,maxZoom);
})();
