/* v2.4 explicit-context Leaflet adapter. */
(function(){
  function createLeafletTravelAdapter(ctx){
    function renderMarkers(day=null){ctx.state.selectedDay=day;const clusters=ctx.leaflet.clusters;if(!clusters)return;clusters.clearLayers();ctx.visiblePoints(day).forEach(point=>{const marker=ctx.leaflet.markers.get(point.id);if(marker)clusters.addLayer(marker)})}
    function renderRoute(day=null){const layer=ctx.leaflet.routeLayer;if(!layer)return;layer.clearLayers();if(!ctx.state.routeVisible||ctx.state.recommendationMode){ctx.setDayRouteCard(null);return}const L=ctx.L();if(!day){ctx.setDayRouteCard(null);ctx.schedules().forEach(schedule=>{const points=ctx.routePoints(schedule);if(points.length<2)return;L.polyline(points.map(p=>[p.lat,p.lng]),{color:'#fff',weight:5,opacity:.65,lineJoin:'round',interactive:false}).addTo(layer);L.polyline(points.map(p=>[p.lat,p.lng]),{color:schedule.color,weight:2.5,opacity:.58,dashArray:'5 8',lineJoin:'round'}).bindTooltip('8/'+schedule.date.slice(3)+' '+schedule.title+'<br>总览仅显示线路范围').addTo(layer)});return}const schedule=ctx.schedules().find(item=>item.date===day);if(!schedule)return;const points=ctx.routePoints(schedule),order=ctx.routeOrderMap(schedule);ctx.setDayRouteCard(schedule);if(points.length<2)return;const coords=points.map(p=>[p.lat,p.lng]);L.polyline(coords,{color:'#fff',weight:11,opacity:.94,lineCap:'round',lineJoin:'round',interactive:false}).addTo(layer);L.polyline(coords,{color:schedule.color,weight:6,opacity:1,lineCap:'round',lineJoin:'round'}).addTo(layer);order.forEach((numbers,id)=>{const point=ctx.pointById(id);if(point)L.marker([point.lat,point.lng],{icon:ctx.routeMarkerIcon(schedule.color,numbers.join('/'),point),zIndexOffset:700}).bindPopup(ctx.popup(point),{maxWidth:360}).addTo(layer)});for(let index=0;index<points.length-1;index++){const a=points[index],b=points[index+1];if(a.lat===b.lat&&a.lng===b.lng)continue;const map=ctx.leaflet.map,count=map&&map.distance([a.lat,a.lng],[b.lat,b.lng])>18000?2:1;for(let k=1;k<=count;k++){const ratio=count===1?.5:k/(count+1),lat=a.lat+(b.lat-a.lat)*ratio,lng=a.lng+(b.lng-a.lng)*ratio;L.marker([lat,lng],{icon:ctx.directionIcon(schedule.color,ctx.bearingRotation(a,b)),interactive:false,zIndexOffset:500}).addTo(layer)}}}
    function fitPoints(points,maxZoom=13){const map=ctx.leaflet.map;if(!map||!points?.length)return;map.fitBounds(ctx.L().latLngBounds(points.map(p=>[p.lat,p.lng])).pad(.25),{maxZoom})}
    return{id:'leaflet',context:ctx,ready:()=>Boolean(ctx.leaflet.map),resize:()=>{try{ctx.leaflet.map?.invalidateSize()}catch{}},view:()=>{try{const center=ctx.leaflet.map.getCenter();return{center:[center.lng,center.lat],zoom:ctx.leaflet.map.getZoom()}}catch{return null}},setView:view=>{try{if(view?.center)ctx.leaflet.map.setView([view.center[1],view.center[0]],view.zoom,{animate:false})}catch{}},renderMarkers,renderRoute,fitPoints,clearLayer:name=>{if(name==='tripRoutes')ctx.leaflet.routeLayer?.clearLayers?.();if(name==='hotels')ctx.leaflet.hotelLayer?.clearLayers?.()}};
  }
  window.createLeafletTravelAdapter=createLeafletTravelAdapter;
  window.TravelLeafletAdapter=createLeafletTravelAdapter({state:TravelAppContext.state,leaflet:TravelAppContext.leaflet,L:()=>window.L,visiblePoints,schedules:()=>SCHEDULES,routePoints,routeOrderMap,pointById,routeMarkerIcon,popup,directionIcon,bearingRotation,setDayRouteCard});
})();
