import fs from 'node:fs';
import path from 'node:path';
import {parse} from 'acorn';

const ROOT=process.cwd();
const LEGACY=path.join(ROOT,'src-v2/app/legacy-app.js');
function write(file,content){const target=path.join(ROOT,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,content)}
function read(file){return fs.readFileSync(path.join(ROOT,file),'utf8')}
function appendUnique(file,marker,content){const target=path.join(ROOT,file),source=fs.existsSync(target)?fs.readFileSync(target,'utf8'):'';if(!source.includes(marker))fs.writeFileSync(target,source.replace(/\s*$/,'')+'\n'+content+'\n')}

const groups={
  coordinate:new Set(['outOfChina','transformLat','transformLng','wgs84ToGcj02']),
  basemap:new Set(['setBasemapState','createTileLayer','autoSwitchBasemap','switchLeafletBasemap','switchBasemap']),
  amapLoader:new Set(['promptAmapConfig','loadAmapApi','switchToAmap']),
  assistant:new Set(['amapSetStatus','amapShowPane','amapButtonBusy','clearAmapServiceOverlays','toggleAmapServicePanel','amapRenderPlaces','resolveAmapLocation','amapCollectPolyline','amapPlanRoute','bindAmapServiceUI']),
  bootstrap:new Set(['syncViewportHeight','initMap','activateTab','bindTabs','setPanelCollapsed','bindUI','bootstrapApp']),
  weather:new Set(['weatherRainHint','tripWeatherRecord']),
  traffic:new Set(['amapSetTrafficVisible']),
  amapAdapter:new Set(['amapFindClusterPoint'])
};
function groupFor(name){for(const [group,names] of Object.entries(groups))if(names.has(name))return group;return'appState'}

if(fs.existsSync(LEGACY)){
  const source=fs.readFileSync(LEGACY,'utf8');
  if(Buffer.byteLength(source)>8000){
    const ast=parse(source,{ecmaVersion:'latest',sourceType:'script',ranges:true,allowHashBang:true});
    const buckets={appState:[],coordinate:[],basemap:[],amapLoader:[],assistant:[],bootstrap:[],weather:[],traffic:[],amapAdapter:[]};
    for(const node of ast.body){
      if(node.type==='VariableDeclaration'){buckets.appState.push(source.slice(node.start,node.end));continue}
      if(node.type==='FunctionDeclaration'&&node.id?.name){buckets[groupFor(node.id.name)].push(source.slice(node.start,node.end));continue}
      buckets.bootstrap.push(source.slice(node.start,node.end));
    }
    const context=`\n(function(){\n  const state={};\n  Object.defineProperties(state,{\n    selectedDay:{get:()=>selectedDay,set:value=>{selectedDay=value}},routeVisible:{get:()=>routeVisible,set:value=>{routeVisible=value}},recommendationMode:{get:()=>recommendationMode,set:value=>{recommendationMode=value}},selectedPresetId:{get:()=>selectedPresetId,set:value=>{selectedPresetId=value}},mapEngine:{get:()=>mapEngine,set:value=>{mapEngine=value}},activeBasemap:{get:()=>activeBasemap,set:value=>{activeBasemap=value}}\n  });\n  const leaflet={};Object.defineProperties(leaflet,{map:{get:()=>map,set:value=>{map=value}},clusters:{get:()=>clusters,set:value=>{clusters=value}},routeLayer:{get:()=>routeLayer,set:value=>{routeLayer=value}},hotelLayer:{get:()=>hotelLayer,set:value=>{hotelLayer=value}},markers:{get:()=>markers}});\n  const amap={};Object.defineProperties(amap,{instance:{get:()=>amapInstance,set:value=>{amapInstance=value}},markers:{get:()=>amapMarkers,set:value=>{amapMarkers=value}},overlays:{get:()=>amapOverlays,set:value=>{amapOverlays=value}},markerCluster:{get:()=>amapMarkerCluster,set:value=>{amapMarkerCluster=value}},clusterPointMap:{get:()=>amapClusterPointMap,set:value=>{amapClusterPointMap=value}},infoWindow:{get:()=>amapInfoWindow,set:value=>{amapInfoWindow=value}},serviceOverlays:{get:()=>amapServiceOverlays,set:value=>{amapServiceOverlays=value}},currentLocation:{get:()=>amapCurrentLocation,set:value=>{amapCurrentLocation=value}},currentLabel:{get:()=>amapCurrentLabel,set:value=>{amapCurrentLabel=value}},trafficVisible:{get:()=>amapTrafficVisible,set:value=>{amapTrafficVisible=value}}});\n  window.TravelAppContext={state,leaflet,amap,config:Object.freeze({AMAP_JS_KEY,AMAP_SECURITY_CODE,AMAP_WEB_KEY,AMAP_CITY,AMAP_ADCODE,BASEMAP_KEY,PANEL_KEY,TRIP_YEAR,TRIP_WEATHER_CACHE_KEY,AMAP_TRAFFIC_PREF_KEY,LEGEND_STATE_KEY}),data:{points:()=>POINTS,schedules:()=>SCHEDULES,bookings:()=>BOOKINGS,pointById,routePoints},storage:{load:loadJSON,save:saveJSON},ui:{escapeHtml,showMapNotice}};\n})();`;
    write('src-v2/core/app-state.js','/* v2.4 explicit application state and compatibility utilities. */\n'+buckets.appState.join('\n')+context+'\n');
    write('src-v2/map/coordinate-service.js','/* v2.4 coordinate conversion service. */\n'+buckets.coordinate.join('\n')+"\nwindow.TravelCoordinates=Object.freeze({outOfChina,transformLat,transformLng,wgs84ToGcj02});\n");
    write('src-v2/map/basemap-controller.js','/* v2.4 basemap controller. */\n'+buckets.basemap.join('\n')+"\nwindow.TravelBasemapController=Object.freeze({sources:BASEMAPS,fallbackOrder:FALLBACK_ORDER,switch:switchBasemap,switchLeaflet:switchLeafletBasemap,autoFailover:autoSwitchBasemap});\n");
    write('src-v2/map/amap-loader.js','/* v2.4 AMap loader and engine switch. */\n'+buckets.amapLoader.join('\n')+"\nwindow.TravelAmapLoader=Object.freeze({load:loadAmapApi,switchTo:switchToAmap,prompt:promptAmapConfig});\n");
    write('src-v2/ui/amap-assistant-controller.js','/* v2.4 AMap assistant UI controller. */\n'+buckets.assistant.join('\n')+"\nwindow.TravelAmapAssistantController=Object.freeze({bind:bindAmapServiceUI,toggle:toggleAmapServicePanel,planRoute:amapPlanRoute,setStatus:amapSetStatus,showPane:amapShowPane});\n");
    write('src-v2/ui/app-bootstrap.js','/* v2.4 application bootstrap and event wiring. */\n'+buckets.bootstrap.join('\n')+"\nwindow.TravelAppBootstrap=Object.freeze({bootstrap:bootstrapApp,bindUI,initMap,activateTab,setPanelCollapsed});\n");
    appendUnique('src-v2/services/weather-service.js','v2.4 weather bridge',"/* v2.4 weather bridge */\n"+buckets.weather.join('\n'));
    appendUnique('src-v2/services/traffic-service.js','v2.4 traffic bridge',"/* v2.4 traffic bridge */\n"+buckets.traffic.join('\n'));
    appendUnique('src-v2/map/amap-adapter.js','v2.4 cluster bridge',"/* v2.4 cluster bridge */\n"+buckets.amapAdapter.join('\n'));
    write('src-v2/app/legacy-app.js',"/* v2.4: legacy application body fully migrated to explicit modules. */\nwindow.TravelLegacyCompat=Object.freeze({version:'2.4.0',bytes:0});\n");
    write('MIGRATION_V2.4.json',JSON.stringify({version:'2.4.0',legacyBytes:Buffer.byteLength(fs.readFileSync(LEGACY,'utf8')),modules:Object.fromEntries(Object.entries(buckets).map(([key,value])=>[key,value.length]))},null,2)+'\n');
  }
}

const leaflet=`/* v2.4 explicit-context Leaflet adapter. */
(function(){
  function createLeafletTravelAdapter(ctx){
    function renderMarkers(day=null){ctx.state.selectedDay=day;const clusters=ctx.leaflet.clusters;if(!clusters)return;clusters.clearLayers();ctx.visiblePoints(day).forEach(point=>{const marker=ctx.leaflet.markers.get(point.id);if(marker)clusters.addLayer(marker)})}
    function renderRoute(day=null){const layer=ctx.leaflet.routeLayer;if(!layer)return;layer.clearLayers();if(!ctx.state.routeVisible||ctx.state.recommendationMode){ctx.setDayRouteCard(null);return}const L=ctx.L();if(!day){ctx.setDayRouteCard(null);ctx.schedules().forEach(schedule=>{const points=ctx.routePoints(schedule);if(points.length<2)return;L.polyline(points.map(p=>[p.lat,p.lng]),{color:'#fff',weight:5,opacity:.65,lineJoin:'round',interactive:false}).addTo(layer);L.polyline(points.map(p=>[p.lat,p.lng]),{color:schedule.color,weight:2.5,opacity:.58,dashArray:'5 8',lineJoin:'round'}).bindTooltip('8/'+schedule.date.slice(3)+' '+schedule.title+'<br>总览仅显示线路范围').addTo(layer)});return}const schedule=ctx.schedules().find(item=>item.date===day);if(!schedule)return;const points=ctx.routePoints(schedule),order=ctx.routeOrderMap(schedule);ctx.setDayRouteCard(schedule);if(points.length<2)return;const coords=points.map(p=>[p.lat,p.lng]);L.polyline(coords,{color:'#fff',weight:11,opacity:.94,lineCap:'round',lineJoin:'round',interactive:false}).addTo(layer);L.polyline(coords,{color:schedule.color,weight:6,opacity:1,lineCap:'round',lineJoin:'round'}).addTo(layer);order.forEach((numbers,id)=>{const point=ctx.pointById(id);if(point)L.marker([point.lat,point.lng],{icon:ctx.routeMarkerIcon(schedule.color,numbers.join('/'),point),zIndexOffset:700}).bindPopup(ctx.popup(point),{maxWidth:360}).addTo(layer)});for(let index=0;index<points.length-1;index++){const a=points[index],b=points[index+1];if(a.lat===b.lat&&a.lng===b.lng)continue;const map=ctx.leaflet.map,count=map&&map.distance([a.lat,a.lng],[b.lat,b.lng])>18000?2:1;for(let k=1;k<=count;k++){const ratio=count===1?.5:k/(count+1),lat=a.lat+(b.lat-a.lat)*ratio,lng=a.lng+(b.lng-a.lng)*ratio;L.marker([lat,lng],{icon:ctx.directionIcon(schedule.color,ctx.bearingRotation(a,b)),interactive:false,zIndexOffset:500}).addTo(layer)}}}
    function fitPoints(points,maxZoom=13){const map=ctx.leaflet.map;if(!map||!points?.length)return;map.fitBounds(ctx.L().latLngBounds(points.map(p=>[p.lat,p.lng])).pad(.25),{maxZoom})}
    return{id:'leaflet',context:ctx,ready:()=>Boolean(ctx.leaflet.map),resize:()=>{try{ctx.leaflet.map?.invalidateSize()}catch{}},view:()=>{try{const center=ctx.leaflet.map.getCenter();return{center:[center.lng,center.lat],zoom:ctx.leaflet.map.getZoom()}}catch{return null}},setView:view=>{try{if(view?.center)ctx.leaflet.map.setView([view.center[1],view.center[0]],view.zoom,{animate:false})}catch{}},renderMarkers,renderRoute,fitPoints,clearLayer:name=>{if(name==='tripRoutes')ctx.leaflet.routeLayer?.clearLayers?.();if(name==='hotels')ctx.leaflet.hotelLayer?.clearLayers?.()}};
  }
  window.createLeafletTravelAdapter=createLeafletTravelAdapter;
  window.TravelLeafletAdapter=createLeafletTravelAdapter({state:TravelAppContext.state,leaflet:TravelAppContext.leaflet,L:()=>window.L,visiblePoints,schedules:()=>SCHEDULES,routePoints,routeOrderMap,pointById,routeMarkerIcon,popup,directionIcon,bearingRotation,setDayRouteCard});
})();
`;
write('src-v2/map/leaflet-adapter.js',leaflet);

const amap=`/* v2.4 explicit-context AMap adapter. */
(function(){
  function createAmapTravelAdapter(ctx){
    const api=()=>ctx.AMap();
    function pointPosition(point){const converted=ctx.coordinate.wgs84ToGcj02(point.lat,point.lng);return[converted[1],converted[0]]}
    function markerPositionKey(value){const location=ctx.poiLocation(value);return location?location.map(v=>Number(v).toFixed(6)).join(','):''}
    function distanceMeters(a,b){const rad=Math.PI/180,lat1=a[1]*rad,lat2=b[1]*rad,dLat=(b[1]-a[1])*rad,dLng=(b[0]-a[0])*rad,x=Math.sin(dLat/2)**2+Math.cos(lat1)*Math.cos(lat2)*Math.sin(dLng/2)**2;return 6371000*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
    function clearOverlays(){const map=ctx.amap.instance;if(!map)return;const cluster=ctx.amap.markerCluster;if(cluster){try{cluster.setData([])}catch{}try{cluster.setMap?.(null)}catch{}ctx.amap.markerCluster=null}try{ctx.amap.infoWindow?.close()}catch{};[...(ctx.amap.markers||[]),...(ctx.amap.overlays||[])].forEach(item=>{try{map.remove(item)}catch{}});ctx.amap.markers=[];ctx.amap.overlays=[];ctx.amap.clusterPointMap=new Map()}
    function findClusterPoint(position){const key=markerPositionKey(position),map=ctx.amap.clusterPointMap;if(map?.has(key))return map.get(key);const location=ctx.poiLocation(position);return ctx.visiblePoints(ctx.state.selectedDay).find(point=>{const p=pointPosition(point);return Math.abs(p[0]-location[0])<.00002&&Math.abs(p[1]-location[1])<.00002})||null}
    function openPoint(id){const point=ctx.pointById(id),map=ctx.amap.instance,A=api();if(!point||!map||!A)return;const position=pointPosition(point);map.setZoomAndCenter(16,position);try{ctx.amap.infoWindow?.close()}catch{}ctx.amap.infoWindow=new A.InfoWindow({content:ctx.popup(point),offset:new A.Pixel(58,-18),closeWhenClickMap:true});ctx.amap.infoWindow.open(map,position)}
    function renderClusterPoint(context){const A=api(),marker=context.marker,point=findClusterPoint(marker.getPosition());if(!point||!A)return;marker.setContent('<div class="amap-travel-marker">'+ctx.renderModel.markerHtml(point)+'</div>');marker.setOffset(new A.Pixel(-15,-16));marker.setTitle(point.name);marker.setExtData(point.id);if(!marker.__travelPointBound){marker.on('click',()=>openPoint(marker.getExtData()));marker.__travelPointBound=true}}
    function renderClusterBadge(context){const A=api(),count=context.count,size=Math.min(48,30+Math.round(Math.log2(Math.max(2,count))*4));context.marker.setContent('<div class="amap-cluster-badge" style="width:'+size+'px;height:'+size+'px">'+count+'</div>');context.marker.setOffset(new A.Pixel(-size/2,-size/2))}
    function fitPoints(points,maxZoom=12){const map=ctx.amap.instance,A=api();if(!map||!A||!points?.length)return;const positions=points.map(pointPosition);if(positions.length===1){map.setZoomAndCenter(maxZoom,positions[0]);return}let minLng=Infinity,minLat=Infinity,maxLng=-Infinity,maxLat=-Infinity;positions.forEach(([lng,lat])=>{minLng=Math.min(minLng,lng);minLat=Math.min(minLat,lat);maxLng=Math.max(maxLng,lng);maxLat=Math.max(maxLat,lat)});const bounds=new A.Bounds([minLng,minLat],[maxLng,maxLat]),avoid=innerWidth<=800?[150,210,52,52]:[82,82,82,82],fit=map.getFitZoomAndCenterByBounds(bounds,avoid,maxZoom);if(fit?.length===2)map.setZoomAndCenter(fit[0],fit[1]);else map.setBounds(bounds,false,avoid)}
    function renderAll(){const map=ctx.amap.instance,A=api();if(!map||!A)return;clearOverlays();const points=ctx.visiblePoints(ctx.state.selectedDay),data=points.map(point=>{const lnglat=pointPosition(point);ctx.amap.clusterPointMap.set(markerPositionKey(lnglat),point);return{lnglat,weight:['住宿区域','酒店'].includes(point.category)?5:1,id:point.id}});if(data.length)ctx.amap.markerCluster=new A.MarkerCluster(map,data,{gridSize:38,maxZoom:16,averageCenter:true,clusterByZoomChange:true,renderClusterMarker:renderClusterBadge,renderMarker:renderClusterPoint});const overlays=[];if(ctx.state.routeVisible){const days=ctx.state.selectedDay?ctx.schedules().filter(day=>day.date===ctx.state.selectedDay):ctx.schedules().slice(1);days.forEach(day=>{const route=ctx.routePoints(day),path=route.map(pointPosition);if(path.length<2)return;if(!ctx.state.selectedDay){overlays.push(new A.Polyline({path,strokeColor:'#fff',strokeWeight:5,strokeOpacity:.65,lineJoin:'round',zIndex:40}),new A.Polyline({path,strokeColor:day.color,strokeWeight:3,strokeOpacity:.58,strokeStyle:'dashed',strokeDasharray:[5,8],lineJoin:'round',zIndex:41}));return}overlays.push(new A.Polyline({path,strokeColor:'#fff',strokeWeight:11,strokeOpacity:.94,lineCap:'round',lineJoin:'round',zIndex:45}),new A.Polyline({path,strokeColor:day.color,strokeWeight:6,strokeOpacity:1,lineCap:'round',lineJoin:'round',zIndex:46}));ctx.routeOrderMap(day).forEach((numbers,id)=>{const point=ctx.pointById(id);if(!point)return;const marker=new A.Marker({position:pointPosition(point),content:'<div class="amap-route-marker">'+ctx.renderModel.routeMarkerHtml(day.color,numbers.join('/'),point)+'</div>',offset:new A.Pixel(-15,-17),zIndex:700,extData:id,title:point.name});marker.on('click',()=>openPoint(marker.getExtData()));overlays.push(marker)});for(let index=0;index<path.length-1;index++){const a=path[index],b=path[index+1],count=distanceMeters(a,b)>18000?2:1,rotation=Math.atan2(b[1]-a[1],b[0]-a[0])*180/Math.PI;for(let k=1;k<=count;k++){const ratio=count===1?.5:k/(count+1),position=[a[0]+(b[0]-a[0])*ratio,a[1]+(b[1]-a[1])*ratio];overlays.push(new A.Marker({position,content:'<div class="amap-direction-marker">'+ctx.renderModel.directionHtml(day.color,rotation)+'</div>',offset:new A.Pixel(-14,-14),zIndex:600}))}}})}ctx.amap.overlays=overlays;if(overlays.length)map.add(overlays);const fit=ctx.state.selectedDay?ctx.routePoints(ctx.schedules().find(day=>day.date===ctx.state.selectedDay)):points;fitPoints(fit,ctx.state.selectedDay?15:11)}
    return{id:'amap',context:ctx,ready:()=>Boolean(ctx.amap.instance),resize:()=>{try{ctx.amap.instance?.resize()}catch{}},view:()=>{try{const center=ctx.amap.instance.getCenter();return{center:[center.lng,center.lat],zoom:ctx.amap.instance.getZoom()}}catch{return null}},setView:view=>{try{if(view?.center)ctx.amap.instance.setZoomAndCenter(view.zoom,view.center,true)}catch{}},renderMarkers:renderAll,renderRoute:renderAll,renderAll,fitPoints,clearLayer:name=>{if(name==='tripRoutes'||name==='tripMarkers')clearOverlays();if(name==='serviceSelection')ctx.clearServiceSelection?.()},clearOverlays,pointPosition,markerPositionKey,distanceMeters,openPoint,renderClusterPoint,renderClusterBadge};
  }
  window.createAmapTravelAdapter=createAmapTravelAdapter;
  window.TravelAmapAdapter=createAmapTravelAdapter({state:TravelAppContext.state,amap:TravelAppContext.amap,AMap:()=>window.AMap,coordinate:TravelCoordinates,poiLocation:amapPoiLocation,visiblePoints,schedules:()=>SCHEDULES,routePoints,routeOrderMap,pointById,popup,renderModel:TravelRenderModel,clearServiceSelection:()=>window.TravelCore?.overlays.clear('serviceSelection',TravelAppContext.amap.instance)});
  window.clearAmapOverlays=()=>TravelAmapAdapter.clearOverlays();window.amapPointPosition=point=>TravelAmapAdapter.pointPosition(point);window.amapMarkerPositionKey=value=>TravelAmapAdapter.markerPositionKey(value);window.amapOpenPoint=id=>TravelAmapAdapter.openPoint(id);window.amapRenderClusterPoint=context=>TravelAmapAdapter.renderClusterPoint(context);window.amapRenderClusterBadge=context=>TravelAmapAdapter.renderClusterBadge(context);window.amapDistanceMeters=(a,b)=>TravelAmapAdapter.distanceMeters(a,b);window.amapFitTravelPoints=(points,maxZoom)=>TravelAmapAdapter.fitPoints(points,maxZoom);
})();
`;
write('src-v2/map/amap-adapter.js',amap);

const registry=`/* v2.4 adapter registry with explicit-context factories. */
function rebuildMarkers(day=null){return window.TravelMapAdapters?.renderMarkers(day,'leaflet')}
function drawRoutes(day=null){return window.TravelMapAdapters?.renderRoute(day,'leaflet')}
function fitPoints(points,maxZoom=13){return window.TravelMapAdapters?.fitPoints(points,maxZoom,'leaflet')}
function renderAmapView(){return window.TravelMapAdapters?.renderRoute(null,'amap')}
function syncAmapView(){if(TravelAppContext.state.mapEngine==='amap'&&TravelAppContext.amap.instance)return window.TravelMapAdapters?.renderRoute(TravelAppContext.state.selectedDay,'amap')}
(function(){const registry=new Map();function register(adapter){if(!adapter?.id)throw new Error('Map adapter id is required');registry.set(adapter.id,adapter);return adapter}register(window.TravelLeafletAdapter);register(window.TravelAmapAdapter);function engine(){return TravelAppContext.state.mapEngine==='amap'?'amap':'leaflet'}function get(id=engine()){return registry.get(id)}function snapshot(){const adapter=get();return{engine:engine(),view:adapter?.view?.()||null,adapters:[...registry.keys()],explicitContext:[...registry.values()].every(item=>Boolean(item.context))}}window.TravelMapAdapters={register,get,current:()=>get(),engine,snapshot,renderMarkers:(day,id=engine())=>get(id)?.renderMarkers?.(day),renderRoute:(day,id=engine())=>get(id)?.renderRoute?.(day),setView:(view,id=engine())=>get(id)?.setView?.(view),fitPoints:(points,maxZoom,id=engine())=>get(id)?.fitPoints?.(points,maxZoom),clearLayer:(name,id=engine())=>get(id)?.clearLayer?.(name),resize:(id=engine())=>get(id)?.resize?.()}})();
`;
write('src-v2/map/map-adapters.js',registry);

write('src-v2/services/service-result.js',`/* v2.4 common service result envelope. */\n(function(){function reportedAt(){return new Date().toISOString()}function success(data,{source='unknown',cached=false,at=reportedAt()}={}){return{ok:true,data,error:null,source,cached:Boolean(cached),reportedAt:at}}function failure(error,{source='unknown',cached=false,at=reportedAt(),data=null}={}){const normalized=error instanceof Error?{name:error.name,message:error.message}:{name:'Error',message:String(error||'未知错误')};return{ok:false,data,error:normalized,source,cached:Boolean(cached),reportedAt:at}}function isResult(value){return Boolean(value&&typeof value==='object'&&typeof value.ok==='boolean'&&'source'in value&&'cached'in value&&'reportedAt'in value)}window.TravelServiceResult=Object.freeze({success,failure,isResult,reportedAt})})();\n`);

write('src-v2/app/legacy-app.js',fs.existsSync(LEGACY)?fs.readFileSync(LEGACY,'utf8'):"/* v2.4 legacy-free marker */\n");
console.log('v2.4 architecture migration ready');
