import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import crypto from 'node:crypto';
import {gunzipSync,gzipSync} from 'node:zlib';

const ROOT=process.cwd(),VERSION='2.4.0',FALLBACK='1.0.15',DATE='2026-07-28';
function fail(message){throw new Error(message)}
function read(...parts){return fs.readFileSync(path.join(ROOT,...parts),'utf8')}
function decode(version){const dir=path.join(ROOT,'assets',`v${version}`),names=fs.readdirSync(dir).filter(name=>/^payload-\d+\.b64$/.test(name)).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));if(names.length!==4)fail(`Expected four payload chunks for v${version}`);const parts=names.map(name=>{const clean=read('assets',`v${version}`,name).replace(/[^A-Za-z0-9+/=]/g,''),core=clean.replace(/=/g,'');if(core.length%4===1)fail(`${name}: invalid base64`);return Buffer.from(core+'='.repeat((4-core.length%4)%4),'base64')});return gunzipSync(Buffer.concat(parts)).toString('utf8')}

const html=decode(VERSION),source=read('src',`v${VERSION}.html`);if(html!==source)fail('Generated source and payload differ');
const hash=crypto.createHash('sha256').update(html).digest('hex');if(!read('DEPLOYMENT.md').includes(hash))fail('Deployment hash mismatch');
for(const token of [`content="${VERSION}"`,`const APP_VERSION='${VERSION}'`,`travel-plans-v${VERSION}`,'window.TravelAppContext','window.TravelCoordinates','window.TravelBasemapController','window.TravelAmapLoader','window.TravelAppBootstrap','window.TravelRenderModel','window.TravelMapAdapters','window.TravelServiceResult','window.TravelServiceFacade','window.TravelLazyTools'])if(!html.includes(token))fail(`Missing v2.4 initial feature: ${token}`);
for(const stale of ['QINGDAO · COUPLE TRIP · v2.3.0','travel-plans-v2.3.0'])if(html.includes(stale))fail(`Stale v2.3 identity in v2.4 page: ${stale}`);
[...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)].forEach((match,index)=>new vm.Script(match[1],{filename:`v2-inline-${index}.js`}));
const lazy=read('assets',`v${VERSION}`,'lazy-tools.js');new vm.Script(lazy,{filename:'lazy-tools.js'});for(const token of ['window.TravelRiskMetrics','window.TravelTripOperations','window.TravelCalendarExport','window.TravelLocalData','trip-stop-status-v2.4','routeEntries','rankAlternatives','apparent_temperature','api.open-meteo.com/v1/elevation'])if(!lazy.includes(token))fail(`Lazy tools missing ${token}`);
if(html.includes('window.TravelTripOperations='))fail('Trip operations must not be included in the initial HTML bundle');

const worker=read('service-worker.js');new vm.Script(worker,{filename:'service-worker.js'});for(const token of ['SKIP_WAITING','CACHE_OFFLINE_CORE','OFFLINE_CORE_READY',`assets/v${VERSION}/lazy-tools.js`])if(!worker.includes(token))fail(`Service worker missing ${token}`);
const loader=read('index.html'),loaderScript=loader.match(/<script>([\s\S]*?)<\/script>/i)?.[1];if(!loaderScript)fail('Root loader script missing');new vm.Script(loaderScript,{filename:'index-loader.js'});if(!loader.includes(`['${VERSION}','${FALLBACK}']`))fail('Root fallback order is incorrect');if(!read('versions',`${DATE}-v${VERSION}.html`).includes(`['${VERSION}']`))fail('Historical v2.4.0 loader is not pinned');if(!fs.existsSync(path.join(ROOT,'versions','2026-07-27-v1.0.15.html')))fail('Stable v1.0.15 historical entry is missing');

const required=['styles/v2.4.css','core/app-state.js','map/coordinate-service.js','map/basemap-controller.js','map/amap-loader.js','ui/amap-assistant-controller.js','ui/app-bootstrap.js','ui/trip-tools-loader.js','map/render-model.js','map/leaflet-adapter.js','map/amap-adapter.js','map/map-adapters.js','services/service-result.js','services/service-facade.js','services/risk-metrics-service.js','services/weather-service.js','services/traffic-service.js','services/search-service.js','services/calendar-export.js','state/local-data-manager.js','ui/trip-operations.js'];for(const file of required)if(!fs.existsSync(path.join(ROOT,'src-v2',file)))fail(`Canonical v2.4 module missing: ${file}`);
for(const file of ['points.js','schedules.js','hotels.js','bookings.js','sources.js','recommendations.js','schema-report.js','catalog.js'])if(!fs.existsSync(path.join(ROOT,'src-v2','data','generated',file)))fail(`Data module missing: ${file}`);
const schema=JSON.parse(read('DATA_SCHEMA_REPORT_v2.4.json'));if(!schema.valid||schema.errors.length)fail(`Data Schema failed: ${schema.errors.join('; ')}`);
const migration=JSON.parse(read('MIGRATION_V2.4.json')),legacy=read('src-v2','app','legacy-app.js');if(Buffer.byteLength(legacy)>1000)fail(`legacy-app.js is not eliminated: ${Buffer.byteLength(legacy)} bytes`);if(migration.legacyBytes>1000)fail(`Migration report legacy size too large: ${migration.legacyBytes}`);

const leaflet=read('src-v2','map','leaflet-adapter.js'),amap=read('src-v2','map','amap-adapter.js'),registry=read('src-v2','map','map-adapters.js');for(const token of ['createLeafletTravelAdapter','context:ctx','ctx.leaflet','ctx.state'])if(!leaflet.includes(token))fail(`Leaflet explicit context missing ${token}`);for(const token of ['createAmapTravelAdapter','context:ctx','ctx.amap','ctx.renderModel'])if(!amap.includes(token))fail(`AMap explicit context missing ${token}`);for(const token of ['explicitContext','renderMarkers','renderRoute','setView','clearLayer','fitPoints'])if(!registry.includes(token))fail(`Adapter registry missing ${token}`);
const serviceResult=read('src-v2','services','service-result.js'),facade=read('src-v2','services','service-facade.js');for(const token of ['ok:true','data','error:null','source','cached','reportedAt'])if(!serviceResult.includes(token))fail(`Service result shape missing ${token}`);for(const token of ["install('weather'","install('traffic'","install('search'","install('location'","install('route'"])if(!facade.includes(token))fail(`Service facade missing ${token}`);
const operations=read('src-v2','ui','trip-operations.js'),risk=read('src-v2','services','risk-metrics-service.js');for(const token of ['trip-stop-status-v2.4','occurrence','routeEntries','migrateStops','rankAlternatives','detourKm'])if(!operations.includes(token))fail(`Occurrence/rain optimization missing ${token}`);for(const token of ['/v3/direction/walking','api.open-meteo.com/v1/elevation','apparent_temperature','ascent','cached:true'])if(!risk.includes(token))fail(`Risk metrics missing ${token}`);
const budget=JSON.parse(read('BUNDLE_BUDGET_v2.4.json')),manifest=JSON.parse(read('assets',`v${VERSION}`,'manifest.json'));if(!budget.passed||budget.initialGzip>=budget.previousInitialGzip)fail('Initial bundle was not reduced');if(manifest.gzipBytes!==gzipSync(Buffer.from(html),{level:9,mtime:0}).length)fail('Manifest initial gzip mismatch');if(manifest.lazyGzipBytes!==gzipSync(Buffer.from(lazy),{level:9,mtime:0}).length)fail('Manifest lazy gzip mismatch');

console.log(`Validation OK: v${VERSION}, initial=${manifest.gzipBytes}, lazy=${manifest.lazyGzipBytes}, legacy=${migration.legacyBytes}, schema=${schema.valid}, explicit adapters and unified services passed`);
