import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import crypto from 'node:crypto';
import { gunzipSync } from 'node:zlib';

const ROOT=process.cwd(),VERSION='1.0.14',FALLBACK='1.0.13';
function fail(message){throw new Error(message)}
function decodeVersion(version){const dir=path.join(ROOT,'assets',`v${version}`),names=fs.readdirSync(dir).filter(name=>/^payload-\d+\.b64$/.test(name)).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));if(names.length!==4)fail(`v${version}: expected 4 payload files, got ${names.length}`);const buffers=names.map(name=>{const raw=fs.readFileSync(path.join(dir,name),'utf8'),clean=raw.replace(/[^A-Za-z0-9+/=]/g,'');if(clean!==raw.trim())fail(`${name}: non-Base64 characters found`);const core=clean.replace(/=/g,'');if(core.length%4===1)fail(`${name}: invalid Base64 length`);return Buffer.from(core+'='.repeat((4-core.length%4)%4),'base64')});const gzip=Buffer.concat(buffers);if(gzip[0]!==0x1f||gzip[1]!==0x8b)fail(`v${version}: invalid gzip signature`);const html=gunzipSync(gzip).toString('utf8');if(!/^\s*(?:<!doctype html|<html)/i.test(html))fail(`v${version}: decompressed content is not HTML`);return{html,gzip}}

const {html,gzip}=decodeVersion(VERSION),source=fs.readFileSync(path.join(ROOT,'src',`v${VERSION}.html`),'utf8');
if(html!==source)fail('Generated source and compressed payload differ');
const hash=crypto.createHash('sha256').update(html).digest('hex'),deployment=fs.readFileSync(path.join(ROOT,'DEPLOYMENT.md'),'utf8');if(!deployment.includes(hash))fail('DEPLOYMENT.md SHA-256 does not match generated HTML');
const identity=[`<meta name="travel-map-version" content="${VERSION}">`,`QINGDAO · COUPLE TRIP · v${VERSION}`,`const APP_VERSION='${VERSION}'`,`travel-plans-v${VERSION}`,'<title>青岛旅行计划</title>'];for(const token of identity)if(!html.includes(token))fail(`Version identity missing: ${token}`);if(html.includes('<title>青岛情侣旅行计划｜2026.08.09–08.16</title>'))fail('Old browser title remains');
const required=['AMap.MarkerCluster','amapRenderClusterBadge','travelMarkerHtml','travelRouteMarkerHtml','travelDirectionHtml','id="amapTrafficRadius"','id="amapTrafficLevel"','id="amapTrafficLayerBtn"','id="amapTaxiPickupBtn"','id="amapTaxiRouteBtn"','amapDrivingTrafficBreakdown','day-weather-chip','day-weather-detail','legend-weather-detail','loadTripWeather','100dvh','syncViewportHeight','实时路况图层默认开启','不提供“附近有多少人正在排队打车”的实时人数'];for(const token of required)if(!html.includes(token))fail(`Missing v1.0.14 feature: ${token}`);
for(const token of ['function iconFor(p){return L.divIcon({className:\'\',html:travelMarkerHtml(p)','function routeMarkerIcon(color,label,p){return L.divIcon({className:\'\',html:travelRouteMarkerHtml(color,label,p)','function directionIcon(color,rotation){return L.divIcon({className:\'\',html:travelDirectionHtml(color,rotation)'])if(!html.includes(token))fail('Leaflet is not using a shared marker factory');
const scripts=[...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)];if(!scripts.length)fail('No inline scripts found');scripts.forEach((match,index)=>new vm.Script(match[1],{filename:`v${VERSION}-inline-${index}.js`}));
const loader=fs.readFileSync(path.join(ROOT,'index.html'),'utf8'),loaderScript=loader.match(/<script>([\s\S]*?)<\/script>/i)?.[1];if(!loaderScript)fail('Loader script missing');new vm.Script(loaderScript,{filename:'index-loader.js'});if(!loader.includes(`['${VERSION}','${FALLBACK}']`))fail('Loader fallback order is incorrect');if(!loader.includes(`?loader=${VERSION}`))fail('Loader cache-busting version is missing');if(!loader.includes('<title>青岛旅行计划</title>'))fail('Loader browser title is incorrect');
const history=fs.readFileSync(path.join(ROOT,'versions','2026-07-27-v1.0.14.html'),'utf8');if(!history.includes(`['${VERSION}']`))fail('Historical v1.0.14 loader should load only v1.0.14');
console.log(`Static validation OK: v${VERSION}, gzip=${gzip.length}, html=${html.length}, sha256=${hash}`);

const webKey=html.match(/AMAP_WEB_KEY='([^']+)'/)?.[1];if(!webKey)fail('AMAP_WEB_KEY not found');
async function webApi(endpoint,params){const url=new URL(`https://restapi.amap.com${endpoint}`);Object.entries({...params,key:webKey,output:'JSON'}).forEach(([key,value])=>url.searchParams.set(key,String(value)));const response=await fetch(url,{headers:{'user-agent':'travel-plans-ci/1.0.14'},signal:AbortSignal.timeout(15000)});if(!response.ok)fail(`${endpoint}: HTTP ${response.status}`);const data=await response.json();if(data.status!=='1')fail(`${endpoint}: ${data.info||data.infocode||'API failure'}`);return data}
try{const weather=await webApi('/v3/weather/weatherInfo',{city:'370200',extensions:'all'});if(!weather.forecasts?.[0]?.casts?.length)fail('Weather API returned no forecast casts');const traffic=await webApi('/v3/traffic/status/circle',{location:'120.38,36.066',radius:3000,level:5,extensions:'all'});if(!traffic.trafficinfo)fail('Traffic API returned no trafficinfo');const driving=await webApi('/v3/direction/driving',{origin:'120.3846,36.0671',destination:'120.3322,36.0573',extensions:'all'});if(!driving.route?.paths?.length)fail('Driving route API returned no path');const taxi=await webApi('/v3/place/around',{keywords:'出租车站',location:'120.38,36.066',radius:3000,offset:5});if(!Array.isArray(taxi.pois))fail('Taxi pickup POI API returned invalid data');console.log('Live AMap Web API validation OK: four-day weather, detailed traffic, driving route, taxi pickup POI')}catch(error){const detail=[error?.message,error?.cause?.code,error?.cause?.message].filter(Boolean).join(' ');if(/fetch failed|timed?out|ETIMEDOUT|ENETUNREACH|ECONNRESET|EAI_AGAIN|AbortError/i.test(detail))console.warn('Live AMap validation skipped because the runner cannot reach AMap:',detail);else throw error}
