import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import crypto from 'node:crypto';
import {gunzipSync,gzipSync} from 'node:zlib';

const ROOT=process.cwd(),VERSION='2.5.3',PREVIOUS='2.5.2',FALLBACK='1.0.15',DATE='2026-07-31';
function fail(message){throw new Error(message)}
function read(...parts){return fs.readFileSync(path.join(ROOT,...parts),'utf8')}
function decode(version){const dir=path.join(ROOT,'assets',`v${version}`),names=fs.readdirSync(dir).filter(name=>/^payload-\d+\.b64$/.test(name)).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));if(names.length!==4)fail(`Expected four payload chunks for v${version}`);const parts=names.map(name=>{const clean=read('assets',`v${version}`,name).replace(/[^A-Za-z0-9+/=]/g,''),core=clean.replace(/=/g,'');if(core.length%4===1)fail(`${name}: invalid base64`);return Buffer.from(core+'='.repeat((4-core.length%4)%4),'base64')});return gunzipSync(Buffer.concat(parts)).toString('utf8')}

const html=decode(VERSION),source=read('src',`v${VERSION}.html`);if(html!==source)fail('Generated source and payload differ');
const hash=crypto.createHash('sha256').update(html).digest('hex');if(!read('DEPLOYMENT.md').includes(hash))fail('Deployment hash mismatch');
const initialTokens=[`content="${VERSION}"`,`const APP_VERSION='${VERSION}'`,`travel-plans-v${VERSION}`,'const GIRLFRIEND_WISHLIST=','window.TravelWishlistMap','wishlist-map-marker','window.TravelVersionedStorage','window.TravelStore','window.TravelSelectors','window.TravelAppContext','window.TravelCoordinates','window.TravelBasemapController','window.TravelAmapLoader','window.TravelAppBootstrap','window.TravelRenderModel','window.TravelMapAdapters','window.TravelServiceResult','window.TravelServiceClients','window.TravelServiceFacade','window.TravelAccessibility','window.TravelLayoutCoordinator','window.TravelLazyTools'];
for(const token of initialTokens)if(!html.includes(token))fail(`Missing v2.5.3 initial feature: ${token}`);
for(const stale of [`travel-plans-v${PREVIOUS}`,`assets/v${PREVIOUS}/lazy-tools.js?loader=${PREVIOUS}`])if(html.includes(stale))fail(`Stale v${PREVIOUS} identity in v${VERSION} page: ${stale}`);
[...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)].forEach((match,index)=>new vm.Script(match[1],{filename:`v2-inline-${index}.js`}));
const lazy=read('assets',`v${VERSION}`,'lazy-tools.js');new vm.Script(lazy,{filename:'lazy-tools.js'});
const lazyTokens=['window.TravelSegmentOverrides','window.TravelTrackStore','window.TravelOperationLog','window.TravelFinance','window.TravelRiskMetrics','window.TravelHealthCheck','window.TravelTripOperations','window.TravelGirlfriendWishlist','window.TravelTripToolsLayout','window.TravelCalendarExport','window.TravelLocalData','trip-girlfriend-wishlist-v2.5.1','girlfriendWishlistPanel','tripToolsDashboard','trip-tool-section','data-wishlist-map-mode','wishlist-day-hint','trip-stop-status-v2.5','trip-segment-overrides-v2.5','trip-finance-v2.5','parseGpx','compareNext','undoLast','itineraryEvents','exportAll'];
for(const token of lazyTokens)if(!lazy.includes(token))fail(`Lazy tools missing ${token}`);
if(html.includes('window.TravelTripOperations='))fail('Trip operations must not be included in the initial HTML bundle');

const worker=read('service-worker.js');new vm.Script(worker,{filename:'service-worker.js'});for(const token of ['SKIP_WAITING','CACHE_OFFLINE_CORE','OFFLINE_CORE_READY',`assets/v${VERSION}/lazy-tools.js`])if(!worker.includes(token))fail(`Service worker missing ${token}`);
const loader=read('index.html'),loaderScript=loader.match(/<script>([\s\S]*?)<\/script>/i)?.[1];if(!loaderScript)fail('Root loader script missing');new vm.Script(loaderScript,{filename:'index-loader.js'});if(!loader.includes(`['${VERSION}','${FALLBACK}']`))fail('Root fallback order is incorrect');if(!read('versions',`${DATE}-v${VERSION}.html`).includes(`['${VERSION}']`))fail('Historical v2.5.3 loader is not pinned');if(!fs.existsSync(path.join(ROOT,'versions','2026-07-27-v1.0.15.html')))fail('Stable v1.0.15 historical entry is missing');

const required=['styles/v2.5.css','styles/v2.5.1.css','styles/v2.5.2.css','styles/v2.5.3.css','styles/v2.5.3.css','styles/v2.5.3.css','styles/v2.5.3.css','styles/v2.5.3.css','styles/v2.5.3.css','styles/v2.5.3.css','styles/v2.5.3.css','styles/v2.5.3.css','styles/v2.5.3.css','core/app-state.js','state/versioned-storage.js','state/travel-store.js','state/preferences.js','data/selectors.js','data/wishlist-map-points.js','data/food-precision-v2.5.3.js','map/coordinate-service.js','map/basemap-controller.js','map/amap-loader.js','ui/amap-assistant-controller.js','ui/app-bootstrap.js','ui/accessibility-controller.js','ui/layout-coordinator.js','ui/trip-tools-loader.js','ui/wishlist-panel.js','ui/food-search-panel.js','ui/trip-tools-layout.js','map/render-model.js','map/marker-renderer.js','map/leaflet-adapter.js','map/amap-adapter.js','map/map-adapters.js','services/service-result.js','services/amap-client.js','services/service-facade.js','services/segment-overrides.js','services/track-store.js','services/operation-log.js','services/finance-store.js','services/risk-metrics-service.js','services/health-check.js','services/calendar-export.js','state/local-data-manager.js','ui/trip-operations.js'];
for(const file of required)if(!fs.existsSync(path.join(ROOT,'src-v2',file)))fail(`Canonical v2.5.3 module missing: ${file}`);
for(const file of ['points.js','schedules.js','hotels.js','bookings.js','sources.js','recommendations.js','wishlist.js','schema-report.js','catalog.js'])if(!fs.existsSync(path.join(ROOT,'src-v2','data','generated',file)))fail(`Data module missing: ${file}`);
const schema=JSON.parse(read('DATA_SCHEMA_REPORT_v2.5.3.json'));if(!schema.valid||schema.errors.length)fail(`Data Schema failed: ${schema.errors.join('; ')}`);if(schema.counts.wishlistAttractions!==17||schema.counts.wishlistFood!==12||schema.counts.mappedWishlistFood!==12||schema.counts.wishlistMapPoints!==10)fail(`Wishlist/map counts incomplete: ${JSON.stringify(schema.counts)}`);
const migration=JSON.parse(read('MIGRATION_V2.5.3.json')),legacy=read('src-v2','app','legacy-app.js');if(Buffer.byteLength(legacy)>1000)fail(`legacy-app.js is not eliminated: ${Buffer.byteLength(legacy)} bytes`);if(migration.legacyBytes>1000)fail(`Migration report legacy size too large: ${migration.legacyBytes}`);

const store=read('src-v2','state','travel-store.js'),selectors=read('src-v2','data','selectors.js'),leaflet=read('src-v2','map','leaflet-adapter.js'),amap=read('src-v2','map','amap-adapter.js'),registry=read('src-v2','map','map-adapters.js');
for(const token of ['subscribe','dispatch','toolsDay','wrapGlobals','TravelActions'])if(!store.includes(token))fail(`Observable store missing ${token}`);
for(const token of ['visiblePointsPure','routePointsPure','routeEntriesPure','TravelWishlistMap.visible'])if(!selectors.includes(token))fail(`Pure selectors missing ${token}`);
for(const token of ['createLeafletTravelAdapter','context:ctx','TravelSelectors','TravelStore.state'])if(!leaflet.includes(token))fail(`Leaflet explicit context missing ${token}`);
for(const token of ['createAmapTravelAdapter','context:ctx','TravelSelectors','TravelStore.state'])if(!amap.includes(token))fail(`AMap explicit context missing ${token}`);
for(const token of ['explicitContext','renderMarkers','renderRoute','setView','clearLayer','fitPoints'])if(!registry.includes(token))fail(`Adapter registry missing ${token}`);

const serviceResult=read('src-v2','services','service-result.js'),client=read('src-v2','services','amap-client.js'),facade=read('src-v2','services','service-facade.js');
for(const token of ['ok:true','data','error:null','source','cached','reportedAt'])if(!serviceResult.includes(token))fail(`Service result shape missing ${token}`);
for(const token of ['fetchJson','jsonp','network','timeout','compareModes','health'])if(!client.includes(token))fail(`Pure AMap client missing ${token}`);
if(client.includes("['network','timeout','api','http']"))fail('JSONP fallback must not repeat API or HTTP failures');
for(const token of ["install('weather'","install('traffic'","install('search'","install('location'","install('route'",'invokePure','controllerSeparated:true'])if(!facade.includes(token))fail(`Service facade missing ${token}`);

const operations=read('src-v2','ui','trip-operations.js'),wishlistUi=read('src-v2','ui','wishlist-panel.js'),toolsLayout=read('src-v2','ui','trip-tools-layout.js'),wishlistData=read('src-v2','data','generated','wishlist.js'),wishlistMap=read('src-v2','data','wishlist-map-points.js'),renderModel=read('src-v2','map','render-model.js'),risk=read('src-v2','services','risk-metrics-service.js'),calendar=read('src-v2','services','calendar-export.js'),local=read('src-v2','state','local-data-manager.js');
for(const token of ['trip-stop-status-v2.5','transportCorrectionPanel','trackPanel','financePanel','nextStopPanel','operationLogPanel','healthCheckPanel','syncMapDay','compareNext','undoLast'])if(!operations.includes(token))fail(`Practical travel tools missing ${token}`);
for(const token of ['TravelGirlfriendWishlist','girlfriendWishlistPanel','data-wishlist-done','data-wishlist-map-mode','renderDailyHint','mappedFoods'])if(!wishlistUi.includes(token))fail(`Wishlist UI missing ${token}`);
for(const token of ['TravelTripToolsLayout','tripToolsDashboard','trip-tool-section','data-tool-group','展开常用','全部收起'])if(!toolsLayout.includes(token))fail(`Organized tools layout missing ${token}`);
for(const token of ['mapPoints','wishmap-wanhechun','wishmap-wangjie','wishmap-qianhaiyan','wishmap-lizhizha','wishmap-laoshan-drinks','wishmap-yingkou-seafood','wishmap-jimiya-seafood','wishmap-xiaomujia','wishmap-yunnan-noodle'])if(!wishlistData.includes(token))fail(`Wishlist map data missing ${token}`);
for(const token of ['TravelWishlistMap','markerHtml','eatSvg','buySvg','wishlistPoint:true','setMode','ensureVisible'])if(!wishlistMap.includes(token))fail(`Wishlist shared map model missing ${token}`);
if(!renderModel.includes('TravelWishlistMap.markerHtml'))fail('Shared render model does not use wishlist logo HTML');
for(const token of ['万和春排骨砂锅米饭','王姐烧烤','高家糖球','前海沿','李村脂渣','崂山可乐普通版','崂山白花蛇草水','炒海肠','蛤蜊','梭子蟹','小木家','云南锅锅米线','雕塑岛（日出）','小青岛公园','黄岛金沙滩'])if(!wishlistData.includes(token))fail(`Wishlist canonical data missing ${token}`);
for(const token of ['TravelSegmentOverrides','TravelTrackStore','importedTrack','pathGeometry','apparent_temperature','quality'])if(!risk.includes(token))fail(`Risk metrics missing ${token}`);
for(const token of ['STATUS:${item.status','SEQUENCE:${Number(item.sequence)','itineraryEvents','CANCELLED'])if(!calendar.includes(token))fail(`Calendar update support missing ${token}`);
for(const token of ['exportEntries','importEntries','TravelTrackStore.list','validateImport'])if(!local.includes(token))fail(`Local data transfer missing ${token}`);

const budget=JSON.parse(read('BUNDLE_BUDGET_v2.5.3.json')),manifest=JSON.parse(read('assets',`v${VERSION}`,'manifest.json'));if(!budget.passed||budget.initialGzip>budget.initialBudget||budget.totalGzip>budget.totalBudget)fail('Bundle budget failed');if(manifest.gzipBytes!==gzipSync(Buffer.from(html),{level:9,mtime:0}).length)fail('Manifest initial gzip mismatch');if(manifest.lazyGzipBytes!==gzipSync(Buffer.from(lazy),{level:9,mtime:0}).length)fail('Manifest lazy gzip mismatch');
const pkg=JSON.parse(read('package.json'));if(pkg.version!==VERSION)fail('package.json version mismatch');
console.log(`Validation OK: v${VERSION}, initial=${manifest.gzipBytes}, lazy=${manifest.lazyGzipBytes}, total=${manifest.totalGzipBytes}, schema=${schema.valid}, runtimePoints=${schema.counts.runtimePoints}, wishlist=${schema.counts.wishlistAttractions}+${schema.counts.wishlistFood}, mapPoints=${schema.counts.wishlistMapPoints}`);
