import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import crypto from 'node:crypto';
import {gunzipSync} from 'node:zlib';

const ROOT=process.cwd(),VERSION='2.3.0',FALLBACK='1.0.15';
function fail(message){throw new Error(message)}
function read(...parts){return fs.readFileSync(path.join(ROOT,...parts),'utf8')}
function decode(version){const dir=path.join(ROOT,'assets',`v${version}`),names=fs.readdirSync(dir).filter(name=>/^payload-\d+\.b64$/.test(name)).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));if(names.length!==4)fail(`Expected four payload chunks for v${version}`);const parts=names.map(name=>{const clean=read('assets',`v${version}`,name).replace(/[^A-Za-z0-9+/=]/g,''),core=clean.replace(/=/g,'');if(core.length%4===1)fail(`${name}: invalid base64`);return Buffer.from(core+'='.repeat((4-core.length%4)%4),'base64')});return gunzipSync(Buffer.concat(parts)).toString('utf8')}

const html=decode(VERSION),source=read('src',`v${VERSION}.html`);if(html!==source)fail('Generated source and payload differ');
const hash=crypto.createHash('sha256').update(html).digest('hex');if(!read('DEPLOYMENT.md').includes(hash))fail('Deployment hash mismatch');
for(const token of [`content="${VERSION}"`,`const APP_VERSION='${VERSION}'`,`travel-plans-v${VERSION}`,'window.TravelRenderModel','window.TravelMapAdapters','window.TravelCalendarExport','window.TravelLocalData','window.TravelTripOperations','TRAVEL_SCHEMA_REPORT','系统日历提醒','本机数据管理','当天模式','站点状态','雨天替代建议','交通费用预算','每日简洁路线卡'])if(!html.includes(token))fail(`Missing v2.3 feature: ${token}`);
for(const stale of ['QINGDAO · COUPLE TRIP · v2.2.0','travel-plans-v2.2.0'])if(html.includes(stale))fail(`Stale v2.2 identity in v2.3 page: ${stale}`);
[...html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/gi)].forEach((match,index)=>new vm.Script(match[1],{filename:`v2-inline-${index}.js`}));
const worker=read('service-worker.js');new vm.Script(worker,{filename:'service-worker.js'});for(const token of ['SKIP_WAITING','CACHE_OFFLINE_CORE','OFFLINE_CORE_READY'])if(!worker.includes(token))fail(`Service worker missing ${token}`);

const loader=read('index.html'),loaderScript=loader.match(/<script>([\s\S]*?)<\/script>/i)?.[1];if(!loaderScript)fail('Root loader script missing');new vm.Script(loaderScript,{filename:'index-loader.js'});if(!loader.includes(`['${VERSION}','${FALLBACK}']`))fail('Root fallback order is incorrect');if(!read('versions','2026-07-27-v2.3.0.html').includes(`['${VERSION}']`))fail('Historical v2.3.0 loader is not pinned');if(!fs.existsSync(path.join(ROOT,'versions','2026-07-27-v1.0.15.html')))fail('Stable v1.0.15 historical entry is missing');

const required=['styles/v2.3.css','ui/booking-panel.js','ui/itinerary-panel.js','ui/search-panel.js','ui/hotel-panel.js','ui/trip-operations.js','map/render-model.js','map/marker-renderer.js','map/route-renderer.js','map/leaflet-adapter.js','map/amap-adapter.js','map/map-adapters.js','services/weather-service.js','services/traffic-service.js','services/search-service.js','services/calendar-export.js','state/local-data-manager.js'];for(const file of required)if(!fs.existsSync(path.join(ROOT,'src-v2',file)))fail(`Canonical v2.3 module missing: ${file}`);
for(const file of ['points.js','schedules.js','hotels.js','bookings.js','sources.js','recommendations.js','schema-report.js','catalog.js'])if(!fs.existsSync(path.join(ROOT,'src-v2','data','generated',file)))fail(`Data module missing: ${file}`);
const schema=JSON.parse(read('DATA_SCHEMA_REPORT_v2.3.json'));if(!schema.valid||schema.errors.length)fail(`Data Schema failed: ${schema.errors.join('; ')}`);for(const check of ['点位 ID 唯一','经纬度合法','pointIds 与路线引用存在'])if(!schema.checks.includes(check))fail(`Schema check missing: ${check}`);
const migration=JSON.parse(read('MIGRATION_V2.3.json'));if(!migration.moved?.length&&migration.legacyBytes>65000)fail('Behavior migration did not move functions');if(migration.legacyBytes>=70000)fail(`legacy-app.js remains too large: ${migration.legacyBytes}`);
const legacy=read('src-v2','app','legacy-app.js');for(const name of ['renderBookingChecklist','renderDays','renderHotels','renderSearchResults','rebuildMarkers','drawRoutes','amapWeatherAtCenter','amapTrafficAtCenter','amapSearchPlaces'])if(new RegExp(`function\\s+${name}\\b`).test(legacy))fail(`${name} still lives in legacy-app.js`);

const renderModel=read('src-v2','map','render-model.js'),leaflet=read('src-v2','map','leaflet-adapter.js'),amap=read('src-v2','map','amap-adapter.js'),registry=read('src-v2','map','map-adapters.js');for(const token of ['markerHtml','routeMarkerHtml','directionHtml','layerNames','popup'])if(!renderModel.includes(token))fail(`Render model missing ${token}`);for(const token of ['clusters.clearLayers','L.polyline','routeLayer','leafletRenderMarkers','leafletRenderRoute'])if(!leaflet.includes(token))fail(`Leaflet real renderer missing ${token}`);for(const token of ['AMap.MarkerCluster','AMap.Polyline','amapRenderTravelView','amapOverlays'])if(!amap.includes(token))fail(`AMap real renderer missing ${token}`);for(const token of ['renderMarkers','renderRoute','setView','clearLayer','fitPoints','register'])if(!registry.includes(token))fail(`Map adapter registry missing ${token}`);
const calendar=read('src-v2','services','calendar-export.js'),local=read('src-v2','state','local-data-manager.js'),operations=read('src-v2','ui','trip-operations.js');for(const token of ['BEGIN:VCALENDAR','VALARM','一键生成全部提醒','data-calendar-index'])if(!calendar.includes(token))fail(`Calendar export missing ${token}`);for(const token of ['预约进度','天气快照','底图偏好','离线缓存','全部恢复默认'])if(!local.includes(token))fail(`Local data manager missing ${token}`);for(const token of ['today-mode-enabled','data-stop-status','rainRisk','comfort','taxi_cost','copyDailyCard','data-status-row'])if(!operations.includes(token))fail(`Trip operations missing ${token}`);

for(const file of required.filter(file=>file.endsWith('.js')))new vm.Script(read('src-v2',file),{filename:file});
console.log(`Validation OK: v${VERSION}, html=${Buffer.byteLength(html)}, sha256=${hash}; legacy=${migration.legacyBytes}, schema=${schema.valid}, behavior modules and trip tools passed`);
