/* v2.5 pure AMap Web API client; credential handling intentionally unchanged. */
(function(){
  'use strict';
  const R=window.TravelServiceResult;
  function classified(message,kind,details={}){const error=new Error(message);error.kind=kind;Object.assign(error,details);return error}
  function validate(data){if(data&&(data.status==='1'||data.status===1||data.errcode===0))return data;throw classified(data?.info||data?.errmsg||data?.infocode||'高德服务返回失败','api',{code:data?.infocode||data?.errcode||null,payload:data})}
  async function fetchJson(url,{timeout=12000}={}){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(url.toString(),{mode:'cors',cache:'no-store',signal:controller.signal});if(!response.ok)throw classified('HTTP '+response.status,'http',{status:response.status});return validate(await response.json())}catch(error){if(error?.kind)throw error;if(error?.name==='AbortError')throw classified('高德服务请求超时','timeout');throw classified(error?.message||'高德服务网络错误','network',{cause:error})}finally{clearTimeout(timer)}}
  function jsonp(url){return new Promise((resolve,reject)=>{const callback='__amap_v25_'+Date.now()+'_'+Math.random().toString(36).slice(2),script=document.createElement('script'),timer=setTimeout(()=>finish(classified('高德服务 JSONP 超时','timeout')),12000);function finish(error,data){clearTimeout(timer);try{delete window[callback]}catch{}script.remove();error?reject(error):resolve(data)}window[callback]=data=>{try{finish(null,validate(data))}catch(error){finish(error)}};url.searchParams.set('callback',callback);script.src=url.toString();script.onerror=()=>finish(classified('高德服务 JSONP 网络错误','network'));document.head.appendChild(script)})}
  async function request(endpoint,params={},options={}){const url=new URL('https://restapi.amap.com'+endpoint);Object.entries({...params,key:AMAP_WEB_KEY,output:'JSON'}).forEach(([key,value])=>{if(value!==undefined&&value!==null&&value!=='')url.searchParams.set(key,String(value))});try{return await fetchJson(url,options)}catch(error){if(!['network','timeout'].includes(error.kind)||options.jsonp===false)throw error;return jsonp(url)}}
  try{amapWebRequest=request;window.amapWebRequest=request}catch{window.amapWebRequest=request}
  function result(source,task){const at=new Date().toISOString();return Promise.resolve().then(task).then(data=>R.success(data,{source,cached:false,at})).catch(error=>R.failure(error,{source,cached:false,at}))}
  const locationText=value=>Array.isArray(value)?value.join(','):String(value||'');
  function search(keyword,{city=AMAP_CITY,page=1,size=20}={}){if(!String(keyword||'').trim())return Promise.resolve(R.failure(classified('请输入地点或关键词','validation'),{source:'高德地点搜索'}));return result('高德地点搜索',()=>request('/v3/place/text',{keywords:String(keyword).trim(),city,citylimit:true,page,offset:size,extensions:'all'}))}
  function nearby(keyword,center,{radius=3000,page=1,size=20}={}){if(!String(keyword||'').trim())return Promise.resolve(R.failure(classified('请输入周边搜索关键词','validation'),{source:'高德周边搜索'}));return result('高德周边搜索',()=>request('/v3/place/around',{keywords:String(keyword).trim(),location:locationText(center),radius,page,offset:size,sortrule:'distance',extensions:'all'}))}
  function weather(city=AMAP_ADCODE){return result('高德天气',()=>request('/v3/weather/weatherInfo',{city,extensions:'all'}))}
  function traffic(center,{radius=3000,level=5}={}){return result('高德实时路况',()=>request('/v3/traffic/status/circle',{location:locationText(center),radius,level,extensions:'all'}))}
  function reverse(center,{radius=1000}={}){return result('高德逆地理编码',()=>request('/v3/geocode/regeo',{location:locationText(center),radius,extensions:'all'}))}
  function geocode(address,{city=AMAP_CITY}={}){if(!String(address||'').trim())return Promise.resolve(R.failure(classified('地点不能为空','validation'),{source:'高德地理编码'}));return result('高德地理编码',()=>request('/v3/geocode/geo',{address:String(address).trim(),city}))}
  function ipLocation(){return result('高德IP定位',()=>request('/v3/ip'))}
  function route(origin,destination,mode='walking',{city=AMAP_CITY}={}){const from=locationText(origin),to=locationText(destination);if(!from||!to)return Promise.resolve(R.failure(classified('路线起点和终点不能为空','validation'),{source:'高德路线规划'}));const config=mode==='driving'?['/v3/direction/driving',{origin:from,destination:to,extensions:'all',strategy:10}]:mode==='transit'?['/v3/direction/transit/integrated',{origin:from,destination:to,city,cityd:city,extensions:'all',strategy:0}]:['/v3/direction/walking',{origin:from,destination:to}];return result('高德'+(mode==='driving'?'驾车':mode==='transit'?'公交地铁':'步行')+'路线',()=>request(config[0],config[1]))}
  async function compareModes(origin,destination,options={}){const modes=options.modes||['walking','transit','driving'],entries=await Promise.all(modes.map(async mode=>[mode,await route(origin,destination,mode,options)]));return R.success(Object.fromEntries(entries),{source:'高德多方式路线比较',cached:false})}
  async function health(){const started=performance.now(),checks={};checks.ip=await ipLocation();const center=checks.ip.ok&&checks.ip.data?.rectangle?String(checks.ip.data.rectangle).split(/[;,]/).map(Number):null;checks.weather=await weather(AMAP_ADCODE);return R.success({checks,latencyMs:Math.round(performance.now()-started),center},{source:'高德服务健康检查',cached:false})}
  window.TravelServiceClients=Object.freeze({request,search,nearby,weather,traffic,reverse,geocode,ipLocation,route,compareModes,health,classify:error=>({kind:error?.kind||'unknown',message:error?.message||String(error),status:error?.status||null,code:error?.code||null})});
})();
