/* v2.5 status-aware calendar export with stable UIDs and cancellation updates. */
(function(){
  'use strict';
  const START='2026-08-09';let panel,events=[];
  function shift(date,days){return new Date(Date.parse(`${date}T00:00:00Z`)+days*86400000).toISOString().slice(0,10)}
  function compact(date){return date.replaceAll('-','')}
  function escapeIcs(value){return String(value??'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}
  function bookingOpen(item){const note=String(item.note||''),match=note.match(/(?:提前|参观前)\s*(\d+)\s*日(?:内)?/);if(!match||!item.dates?.length)return[];const days=Number(match[1]);return item.dates.map(mmdd=>({id:`booking-${item.id}-${mmdd}`,date:shift(`2026-${mmdd}`,-days),title:`检查预约开放：${item.name}`,description:`页面资料记录“${match[0]}”。这是预约开放检查日，不是保证有票的截止日。${item.optional?'该项目属于备选行程。':''}`,category:'预约购票',sourceId:item.id,status:'CONFIRMED',sequence:0}))}
  function preparationEvents(){return[
    {id:'hotel-review',date:shift(START,-14),title:'复核青岛酒店订单',description:'核对准确地址、入住联系人、早餐、安静房、免费取消和含税总价。',category:'住宿'},
    {id:'rent-review',date:shift(START,-14),title:'复核租衣妆造订单',description:'确认门店地址、到店时段、妆造时长、押金、归还和雨天取消规则。',category:'订单'},
    {id:'trip-7',date:shift(START,-7),title:'青岛旅行出发前7天检查',description:'逐项核对预约购票、实名信息、酒店地址和交通方案。',category:'出发准备'},
    {id:'trip-4',date:shift(START,-4),title:'青岛旅行出发前4天天气检查',description:'刷新天气、降雨和风力；根据提示准备雨天替代方案。',category:'出发准备'},
    {id:'trip-2',date:shift(START,-2),title:'青岛旅行出发前2天最终检查',description:'下载离线页面，保存订单截图，准备雨具、防晒、补水和常用药。',category:'出发准备'}].map(item=>({...item,status:'CONFIRMED',sequence:0}))}
  function itineraryEvents(){return SCHEDULES.map(day=>{const entries=window.TravelTripOperations?.routeEntries?.(day)||[],states=entries.map(entry=>TravelTripOperations.stopValue(day.date,entry.point.id,entry.occurrence)),allSkipped=states.length&&states.every(value=>value==='skipped'),completed=states.filter(value=>value==='completed').length,description=[day.summary,'路线：'+entries.map(entry=>shortName(entry.point.name)).join(' → '),'进度：'+completed+'/'+states.length+' 已完成','Plan B：'+day.planB].join('\n');return{id:'itinerary-'+day.date,date:'2026-'+day.date,title:'青岛行程｜'+day.title,description,category:'青岛逐日行程',status:allSkipped?'CANCELLED':'CONFIRMED',sequence:states.some(value=>value!=='pending')?1:0,allDay:true}})}
  function build({includeItinerary=false}={}){const bookings=[];for(const item of BOOKINGS||[])bookings.push(...bookingOpen(item));const all=[...preparationEvents(),...bookings,...(includeItinerary?itineraryEvents():[])],unique=new Map(all.map(item=>[item.id,item]));return[...unique.values()].sort((a,b)=>a.date.localeCompare(b.date)||a.title.localeCompare(b.title))}
  function eventIcs(item){const day=compact(item.date),uid=`${item.id}@travel-plans.local`,stamp=new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z'),last=stamp,lines=['BEGIN:VEVENT',`UID:${escapeIcs(uid)}`,`DTSTAMP:${stamp}`,`LAST-MODIFIED:${last}`,`SEQUENCE:${Number(item.sequence)||0}`,`STATUS:${item.status||'CONFIRMED'}`];if(item.allDay){lines.push(`DTSTART;VALUE=DATE:${day}`,`DTEND;VALUE=DATE:${compact(shift(item.date,1))}`)}else lines.push(`DTSTART;TZID=Asia/Shanghai:${day}T090000`,`DTEND;TZID=Asia/Shanghai:${day}T093000`);lines.push(`SUMMARY:${escapeIcs(item.title)}`,`DESCRIPTION:${escapeIcs(item.description)}`,`CATEGORIES:${escapeIcs(item.category||'青岛旅行')}`);if(item.status!=='CANCELLED')lines.push('BEGIN:VALARM','TRIGGER:-PT10M','ACTION:DISPLAY',`DESCRIPTION:${escapeIcs(item.title)}`,'END:VALARM');lines.push('END:VEVENT');return lines.join('\r\n')}
  function calendarIcs(items,name='青岛旅行提醒',method='PUBLISH'){return['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Travel Plans//Qingdao 2026//ZH-CN','CALSCALE:GREGORIAN',`METHOD:${method}`,`X-WR-CALNAME:${escapeIcs(name)}`,...items.map(eventIcs),'END:VCALENDAR',''].join('\r\n')}
  function download(items,name,method='PUBLISH'){const blob=new Blob(['\ufeff',calendarIcs(items,name,method)],{type:'text/calendar;charset=utf-8'});if(window.TravelTripOperations?.downloadBlob)window.TravelTripOperations.downloadBlob(blob,`${name}.ics`);else{const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${name}.ics`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}}
  function mount(){panel=document.getElementById('calendarExportPanel');if(!panel)return;events=build();const itinerary=itineraryEvents(),cancelled=itinerary.filter(item=>item.status==='CANCELLED');panel.innerHTML=`<div class="trip-tool-head"><b>系统日历提醒</b><div><button type="button" id="exportAllCalendar">出发提醒</button><button type="button" id="exportItineraryCalendar">逐日行程更新</button>${cancelled.length?'<button type="button" id="exportCancelledCalendar">取消已跳过日程</button>':''}</div></div><p>网页下载标准 .ics 文件，打开后由系统日历确认导入。逐日行程使用稳定UID；再次导入可更新标题、说明与状态。标记为整日跳过的行程可生成取消事件。</p><div class="calendar-event-list">${events.map((item,index)=>`<div class="calendar-event-row"><div><b>${item.date} · ${item.title}</b><small>${item.description}</small></div><button type="button" data-calendar-index="${index}">单独设置</button></div>`).join('')}</div>`;panel.querySelector('#exportAllCalendar').onclick=()=>download(events,'青岛旅行提醒-全部');panel.querySelector('#exportItineraryCalendar').onclick=()=>download(itinerary,'青岛逐日行程-当前状态');panel.querySelector('#exportCancelledCalendar')?.addEventListener('click',()=>download(cancelled,'青岛逐日行程-取消更新','CANCEL'));panel.addEventListener('click',event=>{const button=event.target.closest('[data-calendar-index]');if(!button)return;const item=events[Number(button.dataset.calendarIndex)];if(item)download([item],`青岛旅行提醒-${item.title.replace(/[\\/:*?"<>|]/g,'-')}`)})}
  const previousAfterBootstrap=window.TravelV2?.afterBootstrap;if(window.TravelV2)window.TravelV2.afterBootstrap=function(){previousAfterBootstrap?.();mount()};
  document.addEventListener('travel:operation',()=>{if(panel)mount()});
  window.TravelCalendarExport={build,itineraryEvents,calendarIcs,download,mount};
})();
