/* v2.5 local capability, synchronization and layout diagnostics. */
(function(){
  'use strict';
  function overlap(a,b){if(!a||!b)return 0;return Math.max(0,Math.min(a.right,b.right)-Math.max(a.left,b.left))*Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top))}
  function visible(node){if(!node)return false;const style=getComputedStyle(node),rect=node.getBoundingClientRect();return style.display!=='none'&&style.visibility!=='hidden'&&!node.hidden&&rect.width>0&&rect.height>0}
  async function storageCheck(){const key='travel-plans-health-'+Date.now();try{localStorage.setItem(key,'1');const ok=localStorage.getItem(key)==='1';localStorage.removeItem(key);return{ok,label:'本机存储',detail:ok?'可写入和读取':'读取结果异常'}}catch(error){return{ok:false,label:'本机存储',detail:error.message}}}
  async function indexedDbCheck(){try{if(!('indexedDB'in window))throw new Error('浏览器不支持 IndexedDB');await TravelTrackStore?.list?.();return{ok:true,label:'轨迹数据库',detail:'IndexedDB 可用'}}catch(error){return{ok:false,label:'轨迹数据库',detail:error.message}}}
  async function permissionCheck(){try{if(!navigator.permissions?.query)return{ok:true,label:'定位权限',detail:'浏览器将在使用时询问'};const status=await navigator.permissions.query({name:'geolocation'});return{ok:status.state!=='denied',label:'定位权限',detail:status.state==='granted'?'已允许':status.state==='prompt'?'使用时询问':'已拒绝'}}catch{return{ok:true,label:'定位权限',detail:'状态无法预读，使用时询问'}}}
  async function cacheCheck(){if(!('serviceWorker'in navigator))return{ok:false,label:'离线能力',detail:'浏览器不支持 Service Worker'};const registration=await navigator.serviceWorker.getRegistration();const cacheKeys='caches'in window?await caches.keys():[];return{ok:Boolean(registration),label:'离线能力',detail:registration?'Service Worker 已注册，缓存空间 '+cacheKeys.filter(key=>key.startsWith('travel-plans')).length+' 个':'尚未完成注册'}}
  function versionCheck(){const meta=document.querySelector('meta[name="travel-map-version"]')?.content,badge=document.querySelector('.eyebrow')?.textContent||'',deployment=document.getElementById('deploymentVersion')?.textContent||'',ok=meta==='2.5.0'&&badge.includes('v2.5.0')&&deployment.includes('v2.5.0');return{ok,label:'版本同步',detail:ok?'页面、徽标和部署标识一致':'检测到版本标识不同步'}}
  function stateCheck(){const snapshot=TravelStore?.snapshot?.(),selected=snapshot?.selectedDay,tools=snapshot?.toolsDay,activeCard=document.querySelector('.day-card.active')?.dataset.day||null,routeCard=document.getElementById('dayRouteCard')?.classList.contains('show'),mismatch=Boolean(selected&&tools&&selected!==tools);return{ok:!mismatch,label:'行程状态同步',detail:mismatch?'地图日期 '+selected+' 与工具日期 '+tools+' 不一致':'地图、工具和路线状态可同步',data:{selected,tools,activeCard,routeCard}}}
  function mapCheck(){const adapters=TravelMapAdapters?.snapshot?.(),engine=TravelStore?.state?.mapEngine||mapEngine,ready=engine==='amap'?TravelAmapAdapter?.ready?.():TravelLeafletAdapter?.ready?.();return{ok:Boolean(adapters?.explicitContext&&ready),label:'地图适配器',detail:(adapters?.explicitContext?'显式上下文；':'上下文异常；')+(ready?engine+' 已就绪':engine+' 尚未就绪')}}
  function layoutCheck(){const nodes=[['行程面板',document.getElementById('panel')],['地图助手',document.getElementById('amapServicePanel')],['路线抽屉',document.getElementById('mobileRouteDrawer')],['底图控制',document.querySelector('.basemap-control')],['路线卡',document.getElementById('dayRouteCard')],['图例',document.getElementById('legend')]].filter(([,node])=>visible(node)),conflicts=[];for(let i=0;i<nodes.length;i++)for(let j=i+1;j<nodes.length;j++){const [aName,a]=nodes[i],[bName,b]=nodes[j],area=overlap(a.getBoundingClientRect(),b.getBoundingClientRect());if(area>1000&&!(/路线抽屉/.test(aName+bName)&&/路线卡|图例/.test(aName+bName)))conflicts.push(aName+' 与 '+bName)}return{ok:conflicts.length===0,label:'布局冲突',detail:conflicts.length?'检测到：'+conflicts.join('、'):'当前可见浮层没有明显遮挡',data:{conflicts}}}
  function servicesCheck(){const snapshot=TravelServiceFacade?.snapshot?.(),expected=['ok','data','error','source','cached','reportedAt'],ok=expected.every(key=>snapshot?.shape?.includes(key));return{ok,label:'服务结果结构',detail:ok?'统一结果字段完整':'服务结果字段缺失'}}
  async function run({online=false}={}){const checks=[await storageCheck(),await indexedDbCheck(),await permissionCheck(),await cacheCheck(),versionCheck(),stateCheck(),mapCheck(),layoutCheck(),servicesCheck()];if(online){const result=await TravelServiceClients.health();checks.push({ok:result.ok,label:'在线服务',detail:result.ok?'天气与定位请求完成，约 '+result.data.latencyMs+' ms':result.error?.message||'在线检查失败',data:result})}const ok=checks.every(item=>item.ok),data={ok,checks,reportedAt:new Date().toISOString(),online};return TravelServiceResult.success(data,{source:'旅行应用健康检查',cached:false})}
  window.TravelHealthCheck=Object.freeze({run,layoutCheck,stateCheck,versionCheck,overlap});
})();
