/* v2.3 behavior-equivalent extraction: AMap search, geocoding and routing services. Generated once, then maintained as canonical source. */
function amapPoiLocation(poi){const value=poi?.location??poi;if(Array.isArray(value))return value.map(Number);if(typeof value==='string')return amapNormalizeLocation(value);if(value&&typeof value.getLng==='function')return[value.getLng(),value.getLat()];if(value&&Number.isFinite(Number(value.lng))&&Number.isFinite(Number(value.lat)))return[Number(value.lng),Number(value.lat)];return null}
function amapLocationText(location){return location?location.map(v=>Number(v).toFixed(6)).join(','):''}
function amapSetInputLocation(id,label,location,poiId=''){const input=document.getElementById(id),loc=amapPoiLocation(location);if(!input||!loc)return;input.value=label||amapLocationText(loc);input.dataset.location=amapLocationText(loc);input.dataset.poiId=poiId||''}
function amapInputLocation(id){const input=document.getElementById(id);return amapNormalizeLocation(input?.dataset.location||'')}
function amapClearInputLocation(id){const input=document.getElementById(id);if(input){delete input.dataset.location;delete input.dataset.poiId}}
function amapEnsureServices(){
  const ready=mapEngine==='amap'&&amapInstance?Promise.resolve(amapInstance):switchToAmap();
  return ready.then(()=>{
    if(amapAssistantReady)return amapInstance;
    amapAutoComplete=new AMap.AutoComplete({city:AMAP_CITY,citylimit:true});
    amapPlaceSearch=new AMap.PlaceSearch({city:AMAP_CITY,citylimit:true,pageSize:12,pageIndex:1,extensions:'all'});
    amapGeocoder=new AMap.Geocoder({city:AMAP_CITY,radius:1200,extensions:'all'});
    amapWeatherService=new AMap.Weather();
    amapGeolocationService=new AMap.Geolocation({enableHighAccuracy:true,timeout:10000,maximumAge:60000,convert:true,showButton:false,showMarker:false,showCircle:false,panToLocation:false,zoomToAccuracy:false});
    amapAssistantReady=true;
    amapSetStatus('高德服务已就绪','ok');
    return amapInstance
  })
}
function amapRenderSuggestions(tips){const box=document.getElementById('amapSuggestions');amapSuggestionPois=(tips||[]).filter(t=>t&&t.name).slice(0,8);if(!amapSuggestionPois.length){box.hidden=true;box.innerHTML='';return}box.innerHTML=amapSuggestionPois.map((tip,index)=>`<button type="button" class="amap-suggestion" data-amap-suggestion="${index}"><b>${escapeHtml(tip.name)}</b><small>${escapeHtml([tip.district,tip.address].filter(Boolean).join(' · ')||'青岛')}</small></button>`).join('');box.hidden=false}
function amapRenderSearchResults(pois,title='搜索结果'){const box=document.getElementById('amapSearchResults');amapSearchPois=(pois||[]).filter(p=>amapPoiLocation(p));if(!amapSearchPois.length){box.innerHTML='<div class="amap-empty">没有找到匹配地点，请换一个关键词或扩大搜索范围。</div>';return}box.innerHTML=`<div class="amap-result-meta"><b>${escapeHtml(title)}</b><span>${amapSearchPois.length} 个结果</span></div>`+amapSearchPois.map((poi,index)=>{const distance=poi.distance?amapFormatDistance(poi.distance):'',type=String(poi.type||'').split(';').slice(0,2).join(' · ');return `<article class="amap-result-card"><h4>${escapeHtml(poi.name||'未命名地点')}</h4><small>${escapeHtml([poi.address,poi.pname,poi.cityname,poi.adname].filter(Boolean).join(' · '))}</small><div class="amap-result-meta"><span>${escapeHtml(type)}</span>${distance?`<span>距中心 ${escapeHtml(distance)}</span>`:''}</div><div class="amap-result-actions"><button type="button" data-amap-result-action="view" data-amap-result-index="${index}">地图查看</button><button type="button" class="primary" data-amap-result-action="route" data-amap-result-index="${index}">去这里</button><button type="button" data-amap-result-action="nav" data-amap-result-index="${index}">高德导航</button></div></article>`}).join('')}
function amapSelectSearchPoi(index,action='view'){const poi=amapSearchPois[Number(index)],location=amapPoiLocation(poi);if(!poi||!location)return;amapSelectedPoi={name:poi.name||'选定地点',location,id:poi.id||''};if(action==='nav'){const uri='https://uri.amap.com/marker?position='+encodeURIComponent(location.join(','))+'&name='+encodeURIComponent(amapSelectedPoi.name)+'&src=travel-plans&coordinate=gaode&callnative=0';window.open(uri,'_blank','noopener');return}switchToAmap().then(()=>{amapMarkSelectedLocation(location,amapSelectedPoi.name);if(action==='route'){amapSetInputLocation('amapRouteTo',amapSelectedPoi.name,location,amapSelectedPoi.id);amapRouteEnd=location;amapShowPane('route');document.getElementById('amapRouteBtn').focus()}else amapSetStatus('已定位：'+amapSelectedPoi.name,'ok')}).catch(error=>amapSetStatus(error.message,'error'))}
function amapResolveInput(id,fallback){const cached=amapInputLocation(id);if(cached)return Promise.resolve(cached);const input=document.getElementById(id),text=input?.value.trim();if(!text&&fallback)return Promise.resolve(fallback);if(!text)return Promise.reject(new Error(id==='amapRouteFrom'?'请填写起点或使用当前位置':'请填写终点'));return amapEnsureServices().then(()=>new Promise((resolve,reject)=>amapGeocoder.getLocation(text,(status,result)=>{const geocode=result?.geocodes?.[0],location=amapPoiLocation(geocode);if(status==='complete'&&location){amapSetInputLocation(id,geocode.formattedAddress||text,location);resolve(location)}else reject(new Error('无法解析地点：'+text))}))) }
function amapClearRouteService(){if(amapRouteService&&typeof amapRouteService.clear==='function'){try{amapRouteService.clear()}catch(e){}}amapRouteService=null;const steps=document.getElementById('amapRouteSteps');if(steps)steps.innerHTML=''}
function amapRouteSummary(mode,result,origin,destination){let distance=0,duration=0,cost='';if(mode==='transit'){const plan=result?.plans?.[0];distance=plan?.walking_distance||result?.distance||0;duration=plan?.time||plan?.duration||0;cost=plan?.cost?` · 约¥${plan.cost}`:''}else{const route=result?.routes?.[0];distance=route?.distance||0;duration=route?.time||route?.duration||0;if(mode==='driving'){const taxi=result?.taxi_cost??result?.taxiCost;if(taxi)cost=` · 预估打车¥${taxi}`}}const modeName=mode==='driving'?'驾车 / 打车':mode==='transit'?'公交地铁':'步行',uri=amapRouteUri(origin,destination,mode,document.getElementById('amapRouteTo').value||'终点'),traffic=mode==='driving'?amapDrivingTrafficBreakdown(result):'';document.getElementById('amapRouteSummary').innerHTML=`<b>${escapeHtml(modeName)} · ${escapeHtml(amapFormatDistance(distance))} · ${escapeHtml(amapFormatDuration(duration))}${escapeHtml(cost)}</b>${traffic}<p>${mode==='driving'?'路线按实时路况规划；打车价格为路线结果估算，不代表叫车平台最终价格。':'路线已绘制到高德地图，下方可查看逐步说明。'}</p><p><a href="${uri}" target="_blank" rel="noopener">在高德地图中继续导航</a></p>`}
function amapReverseLookup(location){const loc=amapPoiLocation(location);return amapEnsureServices().then(()=>new Promise((resolve,reject)=>amapGeocoder.getAddress(loc,(status,result)=>{if(status==='complete'&&result?.regeocode)resolve(result.regeocode);else reject(new Error('未查询到该位置的地址'))}))) }
function amapRenderContext(location,label,regeocode){amapContextLocation=amapPoiLocation(location);amapContextLabel=label||regeocode?.formattedAddress||'地图选点';const pois=regeocode?.pois||[];document.getElementById('amapContextOutput').innerHTML=`<b>${escapeHtml(amapContextLabel)}</b><div>${escapeHtml(amapLocationText(amapContextLocation))}</div>${pois.length?`<div>附近：${pois.slice(0,4).map(p=>escapeHtml(p.name)).join('、')}</div>`:''}<div class="amap-context-actions"><button type="button" data-amap-context="start">设为起点</button><button type="button" data-amap-context="end">设为终点</button><button type="button" data-amap-context="nearby">搜附近餐厅</button></div>`}
function amapHandleMapClick(event){const location=[event.lnglat.lng,event.lnglat.lat];amapMarkSelectedLocation(location,'地图选点');amapShowPane('travel');amapSetStatus('正在查询选点地址…');amapReverseLookup(location).then(regeo=>{amapRenderContext(location,regeo.formattedAddress,regeo);amapSetStatus('已获取地图选点地址','ok')}).catch(error=>{amapRenderContext(location,'地图选点');amapSetStatus(error.message,'error');throw error})}
function amapUseContext(kind){if(!amapContextLocation)return;if(kind==='start'){amapSetInputLocation('amapRouteFrom',amapContextLabel,amapContextLocation);amapRouteStart=amapContextLocation;amapShowPane('route')}else if(kind==='end'){amapSetInputLocation('amapRouteTo',amapContextLabel,amapContextLocation);amapRouteEnd=amapContextLocation;amapShowPane('route')}else{amapShowPane('search');amapNearbySearch('餐厅',amapContextLocation)}}
function amapPopulateTripDestinations(){const select=document.getElementById('amapTripDestination');if(!select||select.options.length>1)return;const seen=new Set();SCHEDULES.slice(1).forEach(day=>{const group=document.createElement('optgroup');group.label=`8月${Number(day.date.slice(3))}日 · ${day.title}`;day.route.forEach(id=>{if(seen.has(id))return;const p=pointById(id);if(!p||['住宿区域','行程节点'].includes(p.category))return;seen.add(id);const option=document.createElement('option');option.value=id;option.textContent=`${pointIcon(id)} ${shortName(p.name)}`;group.appendChild(option)});if(group.children.length)select.appendChild(group)})}
function amapTripAction(action){const id=document.getElementById('amapTripDestination').value,p=pointById(id);if(!p){amapSetStatus('请先选择一个行程目的地','error');return}const location=amapPointPosition(p);if(action==='nav'){launchAmap(id);return}switchToAmap().then(()=>{amapMarkSelectedLocation(location,p.name);if(action==='route'){amapSetInputLocation('amapRouteTo',p.name,location);amapShowPane('route')}else amapSetStatus('已定位：'+p.name,'ok')})}
function amapNormalizeLocation(value){if(Array.isArray(value))return value.map(Number);const parts=String(value||'').split(',').map(Number);return parts.length===2&&parts.every(Number.isFinite)?parts:null}
function amapCenter(){if(mapEngine==='amap'&&amapInstance){const c=amapInstance.getCenter();return[c.lng,c.lat]}if(map){const c=map.getCenter(),gcj=wgs84ToGcj02(c.lat,c.lng);return[gcj[1],gcj[0]]}return[120.38,36.066]}
function amapSetOutput(title,body){const el=document.getElementById('amapContextOutput')||document.getElementById('amapServiceOutput');if(el)el.innerHTML='<h3>'+escapeHtml(title)+'</h3>'+body;amapShowPane('travel')}
function amapValidateResponse(data){if(data&&(data.status==='1'||data.status===1||data.errcode===0))return data;throw new Error(data?.info||data?.infocode||data?.errmsg||'高德服务返回失败')}
function amapJsonp(url){return new Promise((resolve,reject)=>{const callback='__amap_jsonp_'+Date.now()+'_'+Math.random().toString(36).slice(2),script=document.createElement('script'),timer=setTimeout(()=>finish(new Error('高德服务请求超时')),12000);function finish(error,data){clearTimeout(timer);delete window[callback];script.remove();error?reject(error):resolve(data)}window[callback]=data=>finish(null,data);url.searchParams.set('callback',callback);script.src=url.toString();script.onerror=()=>finish(new Error('高德服务网络错误'));document.head.appendChild(script)})}
function amapWebRequest(endpoint,params={}){const url=new URL('https://restapi.amap.com'+endpoint);Object.entries({...params,key:AMAP_WEB_KEY,output:'JSON'}).forEach(([key,value])=>{if(value!==undefined&&value!==null&&value!=='')url.searchParams.set(key,String(value))});return fetch(url.toString(),{mode:'cors',cache:'no-store'}).then(response=>{if(!response.ok)throw new Error('HTTP '+response.status);return response.json()}).then(amapValidateResponse).catch(()=>amapJsonp(url).then(amapValidateResponse))}
function amapFormatDistance(value){const n=Number(value)||0;return n>=1000?(n/1000).toFixed(1)+' km':Math.round(n)+' m'}
function amapFormatDuration(value){let n=Math.round((Number(value)||0)/60);if(n<60)return n+' 分钟';const h=Math.floor(n/60),m=n%60;return h+' 小时'+(m?m+' 分钟':'')}
function amapMarkSelectedLocation(location,name='选定位置'){amapLastLngLat=amapNormalizeLocation(location);if(!amapLastLngLat||!amapInstance||!window.AMap)return;clearAmapServiceOverlays();const marker=new AMap.Marker({position:amapLastLngLat,title:name,label:{content:escapeHtml(name),direction:'right'}});amapServiceOverlays.push(marker);amapInstance.add(marker);amapInstance.setZoomAndCenter(16,amapLastLngLat)}
function amapSearchPlaces(){const input=document.getElementById('amapSearchInput'),keywords=input.value.trim(),button=document.getElementById('amapSearchBtn');if(!keywords){amapSetStatus('请输入地点或关键词','error');input.focus();return Promise.resolve()}document.getElementById('amapSuggestions').hidden=true;amapButtonBusy(button,true,'搜索中…');amapSetStatus('正在搜索“'+keywords+'”…');return amapEnsureServices().then(()=>new Promise((resolve,reject)=>amapPlaceSearch.search(keywords,(status,result)=>status==='complete'?resolve(result):reject(new Error('没有找到匹配地点'))))).then(result=>{amapRenderSearchResults(result?.poiList?.pois||[],'“'+keywords+'”');amapSetStatus('搜索完成','ok')}).catch(error=>{amapRenderSearchResults([]);amapSetStatus(error.message,'error');throw error}).finally(()=>amapButtonBusy(button,false))}
function amapInputTips(){const input=document.getElementById('amapSearchInput'),keywords=input.value.trim();clearTimeout(amapSuggestionTimer);if(keywords.length<2){amapRenderSuggestions([]);return}amapSuggestionTimer=setTimeout(()=>amapEnsureServices().then(()=>amapAutoComplete.search(keywords,(status,result)=>{if(status==='complete')amapRenderSuggestions(result?.tips||[]);else amapRenderSuggestions([])})).catch(()=>{}),220)}
function amapNearbySearch(keyword,center){const target=amapPoiLocation(center)||amapCurrentLocation||amapCenter();amapShowPane('search');amapSetStatus('正在搜索附近'+keyword+'…');return amapEnsureServices().then(()=>new Promise((resolve,reject)=>amapPlaceSearch.searchNearBy(keyword,target,3000,(status,result)=>status==='complete'?resolve(result):reject(new Error('附近没有找到'+keyword))))).then(result=>{amapRenderSearchResults(result?.poiList?.pois||[],'附近'+keyword);amapSetStatus('周边搜索完成','ok')}).catch(error=>{amapRenderSearchResults([]);amapSetStatus(error.message,'error')})}
function amapReverseAtLocation(location=amapContextLocation||amapLastLngLat||amapCenter()){const target=amapPoiLocation(location);amapSetStatus('正在查询地址…');return amapReverseLookup(target).then(regeo=>{amapRenderContext(target,regeo.formattedAddress,regeo);amapSetStatus('地址查询完成','ok')}).catch(error=>amapSetStatus(error.message,'error'))}
function amapStaticMap(){const center=amapCenter(),url=new URL('https://restapi.amap.com/v3/staticmap');url.searchParams.set('key',AMAP_WEB_KEY);url.searchParams.set('location',center.join(','));url.searchParams.set('zoom','13');url.searchParams.set('size','750*420');url.searchParams.set('scale','2');url.searchParams.set('markers','mid,,A:'+center.join(','));amapSetOutput('高德静态地图','<img class="amap-static-image" alt="高德静态地图" src="'+url.toString()+'"><p><a href="'+url.toString()+'" target="_blank" rel="noopener">在新窗口打开高清静态地图</a></p>')}
function amapIpLocate(){return amapWebRequest('/v3/ip').then(data=>{const values=String(data.rectangle||'').split(/[;,]/).map(Number);if(values.length!==4||!values.every(Number.isFinite))throw new Error('IP定位未返回有效范围');const location=[(values[0]+values[2])/2,(values[1]+values[3])/2],label=(data.province||'')+(data.city||'')+'（IP定位）';amapCurrentLocation=location;amapCurrentLabel=label;amapSetInputLocation('amapRouteFrom',label,location);document.getElementById('amapLocationText').textContent=label;return switchToAmap().then(()=>{amapMarkSelectedLocation(location,label);amapSetStatus('已使用IP定位，精度较低','ok');return location})})}
function amapLocate(){const button=document.getElementById('amapLocateBtn');amapButtonBusy(button,true,'定位中…');amapSetStatus('正在获取当前位置…');return amapEnsureServices().then(()=>new Promise((resolve,reject)=>amapGeolocationService.getCurrentPosition((status,result)=>status==='complete'&&result?.position?resolve(result):reject(new Error(result?.message||'浏览器定位失败'))))).then(result=>{const location=amapPoiLocation(result.position);amapCurrentLocation=location;return amapReverseLookup(location).catch(()=>null).then(regeo=>{const label=regeo?.formattedAddress||'当前位置';amapCurrentLabel=label;amapSetInputLocation('amapRouteFrom',label,location);document.getElementById('amapLocationText').textContent=label;amapMarkSelectedLocation(location,'当前位置');amapSetStatus('定位成功','ok');return location})}).catch(()=>amapIpLocate()).catch(error=>{amapSetStatus('定位失败：'+error.message,'error');throw error}).finally(()=>amapButtonBusy(button,false))}
function amapRouteUri(origin,destination,mode,name){const mapMode=mode==='driving'?'car':mode==='transit'?'bus':'walk';return 'https://uri.amap.com/navigation?from='+encodeURIComponent(origin.join(',')+',起点')+'&to='+encodeURIComponent(destination.join(',')+','+(name||'终点'))+'&mode='+mapMode+'&policy=1&src=travel-plans&coordinate=gaode&callnative=0'}
