/* v2.5 GPX parsing and route-track persistence with IndexedDB fallback. */
(function(){
  'use strict';
  const DB='travel-plans-v2.5',STORE='tracks',FALLBACK_KEY='trip-tracks-v2.5',R=6371000;
  function distance(a,b){const rad=Math.PI/180,dLat=(b.lat-a.lat)*rad,dLng=(b.lng-a.lng)*rad,x=Math.sin(dLat/2)**2+Math.cos(a.lat*rad)*Math.cos(b.lat*rad)*Math.sin(dLng/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
  function total(points){let sum=0;for(let i=1;i<(points||[]).length;i++)sum+=distance(points[i-1],points[i]);return sum}
  function normalize(points){const result=[];for(const value of points||[]){const lat=Number(value.lat),lng=Number(value.lng),ele=Number(value.ele),time=value.time||null;if(!Number.isFinite(lat)||!Number.isFinite(lng)||Math.abs(lat)>90||Math.abs(lng)>180)continue;const last=result.at(-1);if(!last||distance(last,{lat,lng})>1)result.push({lat,lng,ele:Number.isFinite(ele)?ele:null,time})}return result}
  function parseGpx(text){const doc=new DOMParser().parseFromString(String(text||''),'application/xml');if(doc.querySelector('parsererror'))throw new Error('GPX 文件格式无效');const nodes=[...doc.querySelectorAll('trkpt,rtept,wpt')],points=normalize(nodes.map(node=>({lat:node.getAttribute('lat'),lng:node.getAttribute('lon'),ele:node.querySelector('ele')?.textContent,time:node.querySelector('time')?.textContent||null})));if(points.length<2)throw new Error('GPX 中没有足够的轨迹点');return{points,distance:Math.round(total(points)),startTime:points.find(p=>p.time)?.time||null,endTime:[...points].reverse().find(p=>p.time)?.time||null}}
  function open(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject(new Error('IndexedDB 不可用'));const req=indexedDB.open(DB,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE))db.createObjectStore(STORE,{keyPath:'day'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error||new Error('无法打开轨迹数据库'))})}
  async function idb(mode,work){const db=await open();try{return await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,mode),store=tx.objectStore(STORE),request=work(store);if(request){request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)}else{tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)}})}finally{db.close()}}
  function fallback(){try{return JSON.parse(localStorage.getItem(FALLBACK_KEY))||{}}catch{return{}}}
  function saveFallback(record){const data=fallback();data[record.day]=record;try{localStorage.setItem(FALLBACK_KEY,JSON.stringify(data))}catch{}return record}
  async function save(day,points,meta={}){const clean=normalize(points);if(clean.length<2)throw new Error('轨迹至少需要两个有效点');const record={day,points:clean,distance:Math.round(total(clean)),name:meta.name||'导入轨迹',source:meta.source||'GPX',importedAt:new Date().toISOString(),startTime:meta.startTime||null,endTime:meta.endTime||null,schemaVersion:1};try{await idb('readwrite',store=>store.put(record));return record}catch{return saveFallback(record)}}
  async function get(day){try{return await idb('readonly',store=>store.get(day))||fallback()[day]||null}catch{return fallback()[day]||null}}
  async function list(){try{return await idb('readonly',store=>store.getAll())}catch{return Object.values(fallback())}}
  async function remove(day){try{await idb('readwrite',store=>store.delete(day))}catch{}const data=fallback();delete data[day];try{localStorage.setItem(FALLBACK_KEY,JSON.stringify(data))}catch{}document.dispatchEvent(new CustomEvent('travel:track-change',{detail:{day,removed:true}}))}
  async function clear(){try{await idb('readwrite',store=>store.clear())}catch{}try{localStorage.removeItem(FALLBACK_KEY)}catch{}document.dispatchEvent(new CustomEvent('travel:track-change',{detail:{clear:true}}))}
  async function importFile(day,file){if(!file)throw new Error('请选择 GPX 文件');const parsed=parseGpx(await file.text()),record=await save(day,parsed.points,{name:file.name,source:'GPX',startTime:parsed.startTime,endTime:parsed.endTime});document.dispatchEvent(new CustomEvent('travel:track-change',{detail:{day,record}}));return record}
  function sample(points,spacing=100,limit=500){if(!points?.length)return[];const output=[points[0]];let accumulated=0;for(let i=1;i<points.length&&output.length<limit;i++){const a=points[i-1],b=points[i],segment=distance(a,b);accumulated+=segment;if(accumulated>=spacing){output.push(b);accumulated=0}}const last=points.at(-1);if(output.at(-1)!==last&&output.length<limit)output.push(last);return output}
  window.TravelTrackStore=Object.freeze({DB,STORE,FALLBACK_KEY,parseGpx,normalize,distance,total,sample,save,get,list,remove,clear,importFile});
})();
