/* v2.3 behavior-equivalent extraction: weather data and rendering. Generated once, then maintained as canonical source. */
function tripIsoDate(date){return `${TRIP_YEAR}-${date}`}
function weatherValue(record,...keys){for(const key of keys){const value=record&&record[key];if(value!==undefined&&value!==null&&value!=='')return String(value)}return'--'}
function weatherIcon(text=''){if(/雷/.test(text))return'⛈️';if(/雨/.test(text))return'🌧️';if(/雪/.test(text))return'🌨️';if(/雾|霾/.test(text))return'🌫️';if(/阴/.test(text))return'☁️';if(/云/.test(text))return'⛅';if(/晴/.test(text))return'☀️';return'🌤️'}
function tripWeatherCompact(date){const record=tripWeatherRecord(date);if(!record)return'⏳ 待预报';const day=weatherValue(record,'dayweather','dayWeather'),low=weatherValue(record,'nighttemp','nightTemp'),high=weatherValue(record,'daytemp','dayTemp');return`${weatherIcon(day)} ${day} ${low}–${high}℃`}
function tripWeatherDetailHtml(date){const record=tripWeatherRecord(date),label=`8月${Number(date.slice(3))}日`;if(!record)return`<div class="day-weather-detail"><div class="day-weather-period"><b>${label} · 尚未进入预报范围</b>高德公开天气接口仅返回当天至第4天的预报，接近出行日期后会自动更新。</div><div class="day-weather-period"><b>当前状态</b>暂无可核验的日程天气，不使用远期预测冒充准确预报。</div><div class="day-weather-note">页面每30分钟刷新一次高德预报缓存。</div></div>`;const day=weatherValue(record,'dayweather','dayWeather'),night=weatherValue(record,'nightweather','nightWeather'),high=weatherValue(record,'daytemp','dayTemp'),low=weatherValue(record,'nighttemp','nightTemp'),dayWind=weatherValue(record,'daywind','dayWind'),nightWind=weatherValue(record,'nightwind','nightWind'),dayPower=weatherValue(record,'daypower','dayPower'),nightPower=weatherValue(record,'nightpower','nightPower');return`<div class="day-weather-detail"><div class="day-weather-period"><b>${weatherIcon(day)} 白天 · ${escapeHtml(day)} · ${escapeHtml(high)}℃</b>${escapeHtml(dayWind)}风 ${escapeHtml(dayPower)}级 · ${weatherRainHint(day)}</div><div class="day-weather-period"><b>${weatherIcon(night)} 夜间 · ${escapeHtml(night)} · ${escapeHtml(low)}℃</b>${escapeHtml(nightWind)}风 ${escapeHtml(nightPower)}级 · ${weatherRainHint(night)}</div><div class="day-weather-note">高德公开接口提供日/夜预报，不提供小时级降雨概率；“有降水可能”依据天气现象字段判断。</div></div>`}
function tripLegendWeatherHtml(date){const record=tripWeatherRecord(date),label=`8月${Number(date.slice(3))}日`;if(!record)return`<div class="legend-weather-detail"><div>${label}天气</div><small>尚未进入高德4日预报范围；接近出行日期后自动显示白天、夜间天气和降水提示。</small></div>`;const day=weatherValue(record,'dayweather','dayWeather'),night=weatherValue(record,'nightweather','nightWeather'),high=weatherValue(record,'daytemp','dayTemp'),low=weatherValue(record,'nighttemp','nightTemp');return`<div class="legend-weather-detail"><div>${label} · ${weatherIcon(day)} ${escapeHtml(day)} / ${escapeHtml(night)} · ${escapeHtml(low)}–${escapeHtml(high)}℃</div><div class="legend-weather-periods"><span><b>白天</b><br>${escapeHtml(day)} · ${weatherRainHint(day)}</span><span><b>夜间</b><br>${escapeHtml(night)} · ${weatherRainHint(night)}</span></div><small>日/夜预报，非小时级降雨概率 · 发布时间 ${escapeHtml(amapTripWeatherReportTime||'--')}</small></div>`}
function applyTripWeather(data){const forecast=data?.forecasts?.[0],casts=forecast?.casts||[];amapTripWeatherByDate={};casts.forEach(cast=>{const date=weatherValue(cast,'date');if(date!=='--')amapTripWeatherByDate[date]=cast});amapTripWeatherReportTime=weatherValue(forecast,'reporttime','reportTime');renderDays();renderLegend(selectedDay||SCHEDULES[1]?.date)}
function loadTripWeather(force=false){if(amapWeatherLoading)return amapWeatherLoading;const cached=loadJSON(TRIP_WEATHER_CACHE_KEY,null),fresh=cached&&Date.now()-Number(cached.savedAt||0)<30*60*1000;if(cached?.data)applyTripWeather(cached.data);if(fresh&&!force)return Promise.resolve(cached.data);amapWeatherLoading=amapWebRequest('/v3/weather/weatherInfo',{city:AMAP_ADCODE,extensions:'all'}).then(data=>{saveJSON(TRIP_WEATHER_CACHE_KEY,{savedAt:Date.now(),data});applyTripWeather(data);return data}).finally(()=>{amapWeatherLoading=null});return amapWeatherLoading}
function amapWeatherAtCenter(){const center=amapCurrentLocation||amapCenter(),box=document.getElementById('amapWeatherCard');box.textContent='正在查询天气…';return amapEnsureServices().then(()=>amapReverseLookup(center)).then(regeo=>{const component=regeo.addressComponent||{},city=component.adcode||component.city||AMAP_CITY;return Promise.all([new Promise((resolve,reject)=>amapWeatherService.getLive(city,(error,data)=>error?reject(error):resolve(data))),new Promise((resolve,reject)=>amapWeatherService.getForecast(city,(error,data)=>error?reject(error):resolve(data))),loadTripWeather(true).catch(()=>null)])}).then(([live,forecast])=>{const casts=forecast?.forecasts||[];box.innerHTML=`<b>${escapeHtml(live?.city||AMAP_CITY)} · ${weatherIcon(live?.weather||'')} ${escapeHtml(live?.weather||'--')} ${escapeHtml(live?.temperature||'--')}℃</b><div>湿度 ${escapeHtml(live?.humidity||'--')}% · ${escapeHtml(live?.windDirection||live?.winddirection||'--')}风 ${escapeHtml(live?.windPower||live?.windpower||'--')}级</div><div>${casts.slice(0,4).map(c=>`${escapeHtml(c.date||c.day||'')}：${escapeHtml(c.dayWeather||c.dayweather||'--')} / ${escapeHtml(c.nightWeather||c.nightweather||'--')} ${escapeHtml(c.nightTemp||c.nighttemp||'--')}–${escapeHtml(c.dayTemp||c.daytemp||'--')}℃`).join('<br>')}</div><small>高德公开天气为当前实况及4日内日/夜预报。</small>`;amapSetStatus('天气已更新','ok')}).catch(error=>{box.textContent='天气查询失败：'+(error.message||error);amapSetStatus('天气查询失败','error');throw error})}
/* v2.4 weather bridge */
function weatherRainHint(text=''){return/雨|雷|冰雹|雪/.test(text)?'有降水可能':'未显示明显降水'}
function tripWeatherRecord(date){return amapTripWeatherByDate[tripIsoDate(date)]||null}
